#!/usr/bin/env python3
"""Build a performance site-audit Markdown report and a static HTML report
from a structured audit.json file.

Usage:
    python3 build_report.py <audit.json> [--out-dir DIR] [--template FILE]

Outputs (under --out-dir, default current directory):
    <slug>-audit.md      Markdown report
    html/<slug>.html     Static HTML report (warm-stone, print-ready)

audit.json is the single source of truth; it is generated by the `draft` step,
not hand-edited. See REFERENCE.md for the schema, thresholds, and section rules.
"""

import argparse
import html
import json
import re
import sys
from datetime import date
from pathlib import Path
from urllib.parse import urlparse

# ── Canonical thresholds: (good_max, ni_max). Below good_max = good;
#    up to ni_max = needs-improvement; above = poor. Units per REFERENCE.md. ──
THRESHOLDS = {
    "LCP": (2.5, 4.0),
    "CLS": (0.1, 0.25),
    "INP": (200, 500),
    "TBT": (200, 600),
    "SI":  (3.4, 5.8),
    "FCP": (1.8, 3.0),
}

METRIC_LABEL = {
    "LCP": "LCP", "CLS": "CLS", "INP": "INP", "TBT": "TBT",
    "SI": "Speed Index", "FCP": "FCP",
    "weight": "Page weight", "requests": "Requests",
}

GLOSSARY = {
    "LCP": ("Largest Contentful Paint",
            "Time to render the largest visible content above the fold. Good < 2.5 s, poor > 4 s."),
    "CLS": ("Cumulative Layout Shift",
            "Sum of unexpected layout movement during load. Good < 0.1, poor > 0.25."),
    "INP": ("Interaction to Next Paint",
            "Time from a user interaction to the next visual response. Good < 200 ms, poor > 500 ms. A field-data metric — not produced by a Lighthouse lab run."),
    "TBT": ("Total Blocking Time",
            "Lab proxy for INP: main-thread time blocked during load. Good < 200 ms."),
    "SI":  ("Speed Index",
            "How quickly content visually populates during load. Good < 3.4 s."),
    "FCP": ("First Contentful Paint",
            "Time to the first text or image painted. Good < 1.8 s."),
    "weight": ("Page weight",
               "Total bytes downloaded to render the page. More weight means longer load, more parsing, more mobile bandwidth."),
    "requests": ("Request count",
                 "Number of HTTP requests to render the page. High counts (> 100) usually signal concatenation/optimisation gaps."),
}

RATING_LABEL = {"good": "Good", "needs-improvement": "Needs improvement",
                "poor": "Poor", "neutral": "—", "na": "N/A"}

# ── Metrics-as-load-timeline presentation ──────────────────────────────────────
# Metric acronym for the rail's secondary line; full name comes from GLOSSARY.
ACR = {"LCP": "LCP", "CLS": "CLS", "INP": "INP", "TBT": "TBT", "SI": "SI", "FCP": "FCP"}

# Plain-language moment each metric marks in the page-load story.
MOMENT = {
    "FCP": "First paint", "LCP": "Main content in", "SI": "Visually complete",
    "TBT": "Ready to respond", "INP": "Stays snappy", "CLS": "Layout settled",
}

# Phases of the load, in narrative order. Page weight / request count are not
# shown here — the Page resources component is their single source of truth.
PHASES = [
    ("Painting the page", "How soon visitors see content", ["FCP", "LCP", "SI"]),
    ("Responding to input", "How quickly the page reacts", ["TBT", "INP"]),
    ("Visual stability", "Whether content stays put while loading", ["CLS"]),
]
METRIC_ORDER = ["FCP", "LCP", "SI", "TBT", "CLS", "INP"]
SCORE_WORD = {"good": "Good", "needs-improvement": "Needs improvement", "poor": "Poor"}

DEV_ICON = {
    "Desktop": ('<svg class="ic" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4">'
                '<rect x="1.5" y="2" width="13" height="9" rx="1"/><path d="M5.5 14h5M8 11v3"/></svg>'),
    "Mobile": ('<svg class="ic" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4">'
               '<rect x="4" y="1.5" width="8" height="13" rx="1.5"/><path d="M7 12.5h2"/></svg>'),
}
EXT_SVG = ('<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.6">'
           '<path d="M6 3.5H3.5v9h9V10M9.5 3.5H13V7M13 3.5L7.5 9"/></svg>')
GLOBE_SVG = ('<svg class="ic" viewBox="0 0 16 16" fill="none" stroke="currentColor" '
             'stroke-width="1.4"><circle cx="8" cy="8" r="6.5"/><path d="M1.5 8h13M8 1.5'
             'c1.8 1.7 2.8 4.1 2.8 6.5S9.8 12.8 8 14.5C6.2 12.8 5.2 10.4 5.2 8S6.2 3.2 8 1.5z"/></svg>')

# ── Page-resources component ───────────────────────────────────────────────────
# Files whose larger device size is under SMALL_BYTES fold into a per-category
# summary row, but only when at least MIN_FOLD of them collapse (no "1 file" rows).
SMALL_BYTES = 10 * 1024
MIN_FOLD = 2

# Category identity: bars/icon-stroke use base; the icon chip uses the light tint.
RES_CAT_ORDER = ["Images", "Font", "Document", "Stylesheet", "Script", "Media", "Other"]
RES_CAT_ICON = {
    "Images": ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9">'
               '<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9.5" r="1.5"/>'
               '<path d="M21 16l-5-5L5 20"/></svg>'),
    "Font": ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9">'
             '<path d="M4 7V5h16v2M9 19h6M12 5v14"/></svg>'),
    "Document": ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9">'
                 '<path d="M6 2h8l4 4v16H6zM14 2v4h4"/></svg>'),
    "Stylesheet": ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9">'
                   '<path d="M4 3h16l-1.5 16L12 21l-6.5-2z"/><path d="M8 8h8M8 12h6"/></svg>'),
    "Script": ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9">'
               '<path d="M8 9l-3 3 3 3M16 9l3 3-3 3M13 6l-2 12"/></svg>'),
    "Media": ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9">'
              '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M10 9l5 3-5 3z"/></svg>'),
    "Other": ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9">'
              '<circle cx="12" cy="12" r="9"/><path d="M12 8v4l3 2"/></svg>'),
}
RES_CHEV = ('<svg class="chev" viewBox="0 0 16 16" fill="none" stroke="currentColor" '
            'stroke-width="2"><path d="M6 4l4 4-4 4"/></svg>')
RES_SCOPES = [("both", "Both"), ("0", "Desktop"), ("1", "Mobile")]
RES_KEY = ["D", "M"]


def rail_pos(key, value):
    """Fraction 0–1 along a good→ni→poor rail (good 0–40%, ni 40–70%, poor 70–100%)."""
    good_max, ni_max = THRESHOLDS[key]
    if value <= 0:
        return 0.02
    if value < good_max:
        return (value / good_max) * 0.40
    if value <= ni_max:
        return 0.40 + ((value - good_max) / (ni_max - good_max)) * 0.30
    return 0.70 + min((value - ni_max) / ni_max, 1) * 0.30


def audit_type_from_source(src):
    s = str(src or "").strip()
    return s.split()[0] if s else "Audit"


def build_groups(data):
    """Normalise metrics into [{device, datasets:[overall?, ...audits]}].

    New schema: metrics.groups[].audits[]. Falls back to the legacy
    metrics.devices[] (each device becomes a single-audit group)."""
    metrics = data.get("metrics") or {}
    groups_raw = metrics.get("groups")
    if not groups_raw:
        groups_raw = [{"device": d.get("name", "Audit"),
                       "audits": [{"type": audit_type_from_source(d.get("source")),
                                   "source": d.get("source"), "perfScore": d.get("perfScore"),
                                   "reportUrl": d.get("reportUrl"), "items": d.get("items") or []}]}
                      for d in (metrics.get("devices") or [])]

    groups = []
    for g in groups_raw:
        audits = g.get("audits") or []
        device = g.get("device", "")
        audit_ds = []
        for a in audits:
            by_key = {it.get("key"): it for it in (a.get("items") or [])}
            audit_ds.append({
                "kind": "audit", "type": a.get("type", "Audit"), "device": device,
                "source": a.get("source", ""), "perfScore": a.get("perfScore"),
                "reportUrl": a.get("reportUrl"),
                "items": [by_key[k] for k in METRIC_ORDER if k in by_key],
            })

        # Per-metric mean across the audits that measured it.
        avg_items = []
        for k in METRIC_ORDER:
            vals = [it["value"] for a in audits for it in (a.get("items") or [])
                    if it.get("key") == k and it.get("value") is not None]
            if vals:
                avg_items.append({"key": k, "value": sum(vals) / len(vals)})
            elif any(it.get("key") == k for a in audits for it in (a.get("items") or [])):
                avg_items.append({"key": k, "value": None, "display": "lab N/A", "rating": "na"})

        scores = [a.get("perfScore") for a in audits if a.get("perfScore") is not None]
        overall = {
            "kind": "average", "type": "Overall", "device": device,
            "source": "Mean of {0} runs ({1})".format(
                len(audits), ", ".join(a.get("type", "Audit") for a in audits)),
            "sourceLinks": [{"type": a.get("type", "Audit"), "url": a.get("reportUrl")}
                            for a in audits if a.get("reportUrl")],
            # Only a genuine average earns a score; a lone contributing score
            # would just repeat its audit's tab, so leave it off the Overall tab.
            "perfScore": int(round(sum(scores) / len(scores))) if len(scores) > 1 else None,
            "items": avg_items,
        }
        # Skip the Overall tab when there's a single audit (it would just duplicate it).
        datasets = ([overall] if len(audits) > 1 else []) + audit_ds
        if datasets:
            groups.append({"device": device, "datasets": datasets})
    return groups


# ── Helpers ──────────────────────────────────────────────────────────────────

def fail(msg):
    sys.stderr.write("error: " + msg + "\n")
    sys.exit(1)


def slugify(text):
    s = re.sub(r"[^a-z0-9]+", "-", str(text).lower()).strip("-")
    return s or "audit"


def attr(text):
    return html.escape(str(text), quote=True)


def display_url(url):
    """Human-readable URL: drop scheme and a trailing slash, keep host + path."""
    s = re.sub(r"^https?://", "", str(url)).rstrip("/")
    return s or str(url)


def site_name(meta):
    """Short site label for headings: the URL host (sans www), else the title
    with a trailing ' — Site Audit' stripped."""
    url = meta.get("url")
    if url:
        host = urlparse(url if "://" in url else "http://" + url).hostname or ""
        host = re.sub(r"^www\.", "", host)
        if host:
            return host
    title = str(meta.get("title", "")).strip()
    return re.sub(r"\s*[—–-]\s*site audit$", "", title, flags=re.I) or "Site"


def inline_html(text):
    out = html.escape(str(text), quote=False)
    out = re.sub(r"`([^`]+)`", lambda m: "<code>" + m.group(1) + "</code>", out)
    out = re.sub(r"\*\*(.+?)\*\*", lambda m: "<strong>" + m.group(1) + "</strong>", out)
    return out


def plain_text(text):
    t = re.sub(r"`([^`]+)`", r"\1", str(text))
    t = re.sub(r"\*\*(.+?)\*\*", r"\1", t)
    return t.strip()


def paragraphs(text):
    return [p.strip() for p in re.split(r"\n\s*\n", str(text or "")) if p.strip()]


def humanize_bytes(n):
    try:
        n = float(n)
    except (TypeError, ValueError):
        return str(n)
    if n >= 1024 * 1024:
        return "{0:.1f} MB".format(n / (1024 * 1024))
    if n >= 1024:
        return "{0:.0f} KB".format(n / 1024)
    return "{0:.0f} B".format(n)


def metric_display(key, value, given):
    if given:
        return given
    if value is None:
        return "—"
    if key in ("LCP", "SI", "FCP"):
        return "{0:.1f} s".format(value)
    if key == "CLS":
        return "{0:.2f}".format(value)
    if key in ("INP", "TBT"):
        return "{0} ms".format(int(round(value)))
    if key == "weight":
        return humanize_bytes(value)
    if key == "requests":
        return str(int(value))
    return str(value)


def metric_rating(key, value, given):
    if given:
        return given
    if value is None or key not in THRESHOLDS:
        return "neutral"
    good_max, ni_max = THRESHOLDS[key]
    if value < good_max:
        return "good"
    if value <= ni_max:
        return "needs-improvement"
    return "poor"


def score_rating(score):
    if score is None:
        return "neutral"
    if score >= 90:
        return "good"
    if score >= 50:
        return "needs-improvement"
    return "poor"


SEV_RANK = {"high": 0, "medium": 1, "low": 2}


def sorted_findings(findings):
    return sorted(findings or [], key=lambda f: SEV_RANK.get(f.get("severity"), 3))


# ── Load & validate ──────────────────────────────────────────────────────────

def load_audit(path):
    try:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail("audit file not found: " + str(path))
    except json.JSONDecodeError as e:
        fail("audit file is not valid JSON: " + str(e))
    if "meta" not in data:
        fail("audit file is missing the 'meta' object")
    return data


def used_glossary(data):
    keys = list(data.get("glossary") or [])
    if keys:
        return [k for k in GLOSSARY if k in keys]
    # fall back to whatever metric keys actually appear
    seen = set()
    for g in build_groups(data):
        for ds in g["datasets"]:
            for item in ds["items"]:
                seen.add(item.get("key"))
    return [k for k in GLOSSARY if k in seen]


# ── Markdown ─────────────────────────────────────────────────────────────────

def _md_sizes(byts, ndev):
    return " / ".join(humanize_bytes(byts[i]) for i in range(min(ndev, len(byts))))


def build_resources_markdown(data):
    res = data.get("resources") or {}
    cats = res.get("categories") or []
    if not cats:
        return []
    devices = res.get("devices") or ["Desktop"]
    ndev = len(devices)
    out = ["## Page resources", ""]
    for para in paragraphs(res.get("intro")):
        out.append(para)
        out.append("")
    head = "| Category | Requests | " + " | ".join(devices[:ndev]) + " |"
    out.append(head)
    out.append("|---|---:|" + "|".join(["---:"] * ndev) + "|")
    for c in cats:
        byts = c.get("bytes", [0])
        sizes = " | ".join(humanize_bytes(byts[i]) for i in range(min(ndev, len(byts))))
        out.append("| {0} | {1} | {2} |".format(
            c.get("type", ""), (c.get("requests") or [""])[0], sizes))
    tot = res.get("total") or {}
    if tot:
        tb = tot.get("bytes", [0])
        sizes = " | ".join(humanize_bytes(tb[i]) for i in range(min(ndev, len(tb))))
        out.append("| **Total** | {0} | {1} |".format((tot.get("requests") or [""])[0], sizes))
    out.append("")
    for c in cats:
        assets = c.get("assets") or []
        big, small = _res_split(assets, ndev)
        foldable = len(small) >= MIN_FOLD
        shown = big if foldable else assets
        if not shown and not foldable:
            continue
        out.append("**{0}**".format(c.get("type", "")))
        out.append("")
        for a in shown:
            ahost = _res_host(a.get("url"))
            au = a.get("url", "")
            # CommonMark: bare link destinations can't hold spaces or unbalanced
            # parens (tracking urls often do); angle-wrap those.
            if any(ch in au for ch in " ()"):
                au = "<" + au + ">"
            host_md = " ([{0}]({1}))".format(ahost, au) if ahost else ""
            out.append("- `{0}`{1} — {2}".format(
                a.get("name", ""), host_md, _md_sizes(a.get("bytes", [0]), ndev)))
        if foldable:
            fk = [sum((a.get("bytes") or [0])[i] for a in small) for i in range(ndev)]
            out.append("- _+{0} files under {1} KB — {2}_".format(
                len(small), SMALL_BYTES // 1024, _md_sizes(fk, ndev)))
        out.append("")
    return out


def build_markdown(data):
    meta = data["meta"]
    out = []
    out.append("# Website Performance Review: " + site_name(meta))
    out.append("")
    bits = []
    if meta.get("url"):
        bits.append("**URL:** " + meta["url"])
    bits.append("**Date:** " + str(meta.get("date", date.today().isoformat())))
    if meta.get("scope"):
        bits.append("**Scope:** " + meta["scope"])
    if meta.get("audience"):
        bits.append("**Audience:** " + meta["audience"])
    out.append(" · ".join(bits))
    out.append("")

    # Summary
    out.append("## Summary")
    out.append("")
    for para in paragraphs(data.get("summary")):
        out.append(para)
        out.append("")

    # Metrics
    out.append("## Metrics")
    out.append("")
    for para in paragraphs((data.get("metrics") or {}).get("intro")):
        out.append(para)
        out.append("")
    for g in build_groups(data):
        out.append("### " + (g["device"] or "Device"))
        out.append("")
        for ds in g["datasets"]:
            name = ("Overall average" if ds["kind"] == "average" else ds["type"])
            head = "#### " + name
            if ds.get("perfScore") is not None:
                head += " — performance score {0}".format(int(ds["perfScore"]))
            out.append(head)
            out.append("")
            meta_bits = []
            if ds.get("source"):
                meta_bits.append("_" + ds["source"] + "_")
            if ds.get("reportUrl"):
                meta_bits.append("[full report]({0})".format(ds["reportUrl"]))
            for l in ds.get("sourceLinks") or []:
                meta_bits.append("[{0}]({1})".format(l["type"], l["url"]))
            if meta_bits:
                out.append(" · ".join(meta_bits))
                out.append("")
            out.append("| Metric | Value | Rating |")
            out.append("|---|---|---|")
            for item in ds["items"]:
                key = item.get("key")
                disp = metric_display(key, item.get("value"), item.get("display"))
                rating = metric_rating(key, item.get("value"), item.get("rating"))
                out.append("| {0} | {1} | {2} |".format(
                    METRIC_LABEL.get(key, key), disp, RATING_LABEL.get(rating, rating)))
            out.append("")

    # Page resources
    res_md = build_resources_markdown(data)
    if res_md:
        out.extend(res_md)

    # Architecture
    if str(data.get("architecture") or "").strip():
        out.append("## Site architecture")
        out.append("")
        for para in paragraphs(data["architecture"]):
            out.append(para)
            out.append("")

    # Performance
    perf = data.get("performance") or {}
    if perf.get("tests") or perf.get("findings"):
        out.append("## Performance")
        out.append("")
        if perf.get("tests"):
            out.append("### Tests")
            out.append("")
            for t in perf["tests"]:
                out.append("- " + t.get("label", "") + ": " + t.get("url", ""))
            out.append("")
        if perf.get("findings"):
            out.append("### Findings")
            out.append("")
            for f in sorted_findings(perf["findings"]):
                title = "**{0}** — {1}".format(f.get("id", ""), f.get("title", ""))
                tags = []
                if f.get("savingsDisplay"):
                    tags.append(f["savingsDisplay"])
                if f.get("confirmed") is False:
                    tags.append("candidate")
                if tags:
                    title += " _(" + ", ".join(tags) + ")_"
                out.append(title)
                out.append("")
                for para in paragraphs(f.get("body")):
                    out.append(para)
                    out.append("")

    # Accessibility
    acc = data.get("accessibility") or {}
    if acc.get("tests") or acc.get("findings"):
        out.append("## Accessibility")
        out.append("")
        if acc.get("tests"):
            out.append("### Tests")
            out.append("")
            for t in acc["tests"]:
                out.append("- " + t.get("label", "") + ": " + t.get("url", ""))
            out.append("")
        if acc.get("findings"):
            out.append("### Findings")
            out.append("")
            for b in acc["findings"]:
                out.append("- " + str(b))
            out.append("")

    # Design & UX
    if data.get("ux"):
        out.append("## Design and user experience")
        out.append("")
        for b in data["ux"]:
            out.append("- " + str(b))
        out.append("")

    # Conclusions
    out.append("## Conclusions")
    out.append("")
    for para in paragraphs(data.get("conclusions")):
        out.append(para)
        out.append("")

    # Priorities
    if data.get("priorities"):
        out.append("### Priority actions")
        out.append("")
        for i, p in enumerate(data["priorities"], 1):
            out.append("{0}. {1}".format(i, p))
        out.append("")

    # Glossary
    gkeys = used_glossary(data)
    if gkeys:
        out.append("## Glossary")
        out.append("")
        for k in gkeys:
            name, desc = GLOSSARY[k]
            out.append("- **{0}** — {1}".format(name, desc))
        out.append("")

    # Appendix
    runs = list(perf.get("tests") or []) + list(acc.get("tests") or [])
    if runs:
        out.append("## Appendix — raw test runs")
        out.append("")
        for t in runs:
            out.append("- " + t.get("label", "") + ": " + t.get("url", ""))
        out.append("")

    return "\n".join(out).rstrip() + "\n"


# ── HTML section builders ────────────────────────────────────────────────────

def nav_link(target, label):
    return ('    <a href="#' + attr(target) + '" class="nav-top-link" data-target="'
            + attr(target) + '">' + html.escape(label) + '</a>')


def prose_block(text, cls="prose"):
    if not str(text or "").strip():
        return ""
    out, para, bullets = [], [], []

    def flush_para():
        if para:
            out.append("      <p>" + inline_html(" ".join(para)) + "</p>")
            para.clear()

    def flush_bullets():
        if bullets:
            out.append('      <ul class="bullets">')
            out.extend("        <li>" + inline_html(b) + "</li>" for b in bullets)
            out.append("      </ul>")
            bullets.clear()

    for raw in str(text).split("\n"):
        line = raw.strip()
        if not line:
            flush_para(); flush_bullets()
            continue
        m = re.match(r"[-*]\s+(.*)", line)
        if m:
            flush_para()
            bullets.append(m.group(1).strip())
        else:
            flush_bullets()
            para.append(line)
    flush_para(); flush_bullets()
    return '    <div class="' + cls + '">\n' + "\n".join(out) + '\n    </div>'


def section(sid, heading, body):
    return ('    <section class="content-section" id="' + attr(sid) + '">\n'
            '      <h2 class="section-heading">' + html.escape(heading) + '</h2>\n'
            + body + '\n    </section>')


def _rail_row_html(item):
    key = item.get("key")
    rating = metric_rating(key, item.get("value"), item.get("rating"))
    disp = metric_display(key, item.get("value"), item.get("display"))
    has_rail = key in THRESHOLDS and item.get("value") is not None
    if has_rail:
        pos = rail_pos(key, item["value"]) * 100
        mid = ('<div class="rail-track"><span class="rail-marker ' + rating
               + '" style="left:{0:.1f}%"></span></div>'.format(pos))
    else:
        mid = '<div class="rail-track"><span class="rail-na">not measured in this run</span></div>'
    full = GLOSSARY.get(key, (key, ""))[0]
    return ('            <div class="tl-row"><div class="tl-label">'
            '<div class="moment">' + html.escape(MOMENT.get(key, key)) + '</div>'
            '<div class="metric"><b>' + html.escape(ACR.get(key, key)) + '</b> · '
            + html.escape(full) + '</div></div>' + mid
            + '<div class="rail-val ' + rating + '">' + html.escape(disp) + '</div></div>')


def _timeline_html(dataset):
    by_key = {it.get("key"): it for it in dataset["items"]}
    rows = ['          <div class="tl">']
    for title, blurb, keys in PHASES:
        present = [by_key[k] for k in keys if k in by_key]
        if not present:
            continue
        rows.append('            <div class="tl-phase"><div class="tl-spine">'
                    '<span class="tl-node"></span></div>')
        rows.append('              <div class="tl-body"><div class="tl-head">'
                    '<div class="tl-title">' + html.escape(title) + '</div>'
                    '<div class="tl-blurb">' + html.escape(blurb) + '</div></div>')
        rows.append("\n".join(_rail_row_html(it) for it in present))
        rows.append('              </div></div>')
    rows.append('          </div>')
    return "\n".join(rows)


def _score_hero_html(dataset):
    if dataset.get("perfScore") is None:
        return ""
    sr = score_rating(dataset["perfScore"])
    sub = ("Averaged across runs" if dataset["kind"] == "average"
           else dataset["type"] + " lab score") + " · " + SCORE_WORD[sr]
    return ('          <div class="score-wrap"><div class="score-hero ' + sr + '">'
            '<div class="score-num">' + str(dataset["perfScore"])
            + '<span class="score-den">/100</span></div>'
            '<div class="score-meta"><div class="score-title">Performance score</div>'
            '<div class="score-sub">' + html.escape(sub) + '</div></div></div></div>')


def _panel_html(dataset, idx, active, device):
    cap_name = ("Overall average for " if dataset["kind"] == "average"
                else dataset["type"] + " for ") + device
    pill = '<span class="cap-avg">averaged</span>' if dataset["kind"] == "average" else ""
    link = ""
    if dataset["kind"] == "audit" and dataset.get("reportUrl"):
        link = ('<a class="cap-link" href="' + attr(dataset["reportUrl"])
                + '" target="_blank" rel="noopener">View full ' + html.escape(dataset["type"])
                + ' report ' + EXT_SVG + '</a>')
    elif dataset["kind"] == "average" and dataset.get("sourceLinks"):
        link = '<span class="cap-srclinks">' + "".join(
            '<a href="' + attr(l["url"]) + '" target="_blank" rel="noopener">'
            + html.escape(l["type"]) + ' ' + EXT_SVG + '</a>'
            for l in dataset["sourceLinks"]) + '</span>'
    cap = ('          <div class="panel-cap"><span class="cap-name">' + html.escape(cap_name)
           + '</span>' + pill + '<span class="cap-src">' + html.escape(dataset.get("source", ""))
           + '</span>' + link + '</div>')
    return ('        <div class="panel' + (' active' if active else '') + '" data-aud="' + str(idx) + '">\n'
            + cap + '\n' + _score_hero_html(dataset) + '\n' + _timeline_html(dataset) + '\n        </div>')


def build_metrics_html(data):
    groups = build_groups(data)
    if not groups:
        return '      <p class="empty-note">No metrics provided.</p>'
    out = ['      <div class="metrics-component">']
    if len(groups) > 1:
        out.append('        <div class="devbar"><span class="dev-lab">Tested on</span>')
        out.append('          <div class="seg">')
        for i, g in enumerate(groups):
            out.append('            <button class="seg-btn' + (' active' if i == 0 else '')
                       + '" data-dev="' + str(i) + '">' + DEV_ICON.get(g["device"], "")
                       + html.escape(g["device"]) + '</button>')
        out.append('          </div></div>')
    for i, g in enumerate(groups):
        out.append('        <div class="dev-group' + (' active' if i == 0 else '')
                   + '" data-dev="' + str(i) + '">')
        out.append('          <div class="tabrow">')
        for j, ds in enumerate(g["datasets"]):
            out.append('            <button class="atab' + (' active' if j == 0 else '')
                       + '" data-aud="' + str(j) + '">' + html.escape(ds["type"]) + '</button>')
        out.append('          </div>')
        out.append('          <div class="panel-stack">')
        for j, ds in enumerate(g["datasets"]):
            out.append(_panel_html(ds, j, j == 0, g["device"]))
        out.append('          </div>')
        out.append('        </div>')
    out.append('      </div>')
    return "\n".join(out)


def _res_cat_key(t):
    """Map a category type to a palette/icon key, defaulting unknowns to Other."""
    return t if t in RES_CAT_ICON else "Other"


def _res_bars(byts, scale, t, ndev, multi):
    key = _res_cat_key(t)
    rows = []
    for i in range(min(ndev, len(byts))):
        w = max(1.5, 100 * byts[i] / scale) if scale else 1.5
        cls = "d" if i == 0 else "m"
        klab = RES_KEY[i] if (multi and i < len(RES_KEY)) else ""
        rows.append('<div class="brow ' + cls + '"><span class="k">' + klab + '</span>'
                    '<div class="track"><div class="fill ' + cls + '" '
                    'style="width:{0:.1f}%;background:var(--cat-{1})"></div></div></div>'.format(w, key))
    return '<div class="bars">' + "".join(rows) + '</div>'


def _res_sizes(byts, ndev):
    lines = []
    for i in range(min(ndev, len(byts))):
        cls = "d" if i == 0 else "m"
        lines.append('<div class="sline ' + cls + '">' + html.escape(humanize_bytes(byts[i])) + '</div>')
    return '<div class="szs">' + "".join(lines) + '</div>'


def _res_split(assets, ndev):
    """Return (big, small): assets whose larger measured size is < SMALL_BYTES are
    'small'. Order within each bucket is preserved."""
    big, small = [], []
    for a in assets:
        byts = a.get("bytes") or [0]
        (small if max(byts[:ndev] or byts) < SMALL_BYTES else big).append(a)
    return big, small


def _res_host(url):
    """Return the lowercased host of an asset url for display, or "" if none."""
    if not url:
        return ""
    return (urlparse(url if "://" in url else "http://" + url).hostname or "").lower()


def _split_name(name):
    """Split a filename into (head, tail) for CSS middle-truncation: the tail is
    pinned (kept whole) so the extension survives; the head ellipsises. Short
    names get an empty tail (no truncation needed)."""
    n = str(name)
    return (n[:-12], n[-12:]) if len(n) > 16 else (n, "")


def build_resources_html(data):
    res = data.get("resources") or {}
    cats = res.get("categories") or []
    if not cats:
        return '      <p class="empty-note">No resource breakdown provided.</p>'
    devices = res.get("devices") or ["Desktop"]
    ndev = len(devices)
    multi = ndev > 1
    cat_scale = max([c.get("bytes", [0])[0] for c in cats] or [0]) or 1

    # header — device toggle (multi) or the single device's name in the bars column
    if multi:
        toggle = '<div class="scope">' + "".join(
            '<button data-scope="' + v + '"' + (' class="active"' if v == "both" else '')
            + '>' + html.escape(lbl) + '</button>' for v, lbl in RES_SCOPES) + '</div>'
    else:
        toggle = '<span class="dev1">' + html.escape(devices[0]) + '</span>'
    out = ['      <div class="res" data-scope="both">',
           '        <div class="res-head"><div>Category / file</div>'
           '<div class="r reqh">Req</div><div class="bcol">' + toggle
           + '</div><div class="r">Size</div></div>']

    for c in cats:
        t = str(c.get("type", "Other"))
        key = _res_cat_key(t)
        assets = c.get("assets") or []
        big, small = _res_split(assets, ndev)
        foldable = len(small) >= MIN_FOLD
        shown = big if foldable else assets
        item_scale = max([max(a.get("bytes", [0])) for a in assets] or [0]) or 1
        req = (c.get("requests") or [""])[0]

        cat_toggle = ''
        if foldable:
            cat_toggle = ('<div class="scope cat-scope">'
                          '<button data-mode="all">All</button>'
                          '<button data-mode="fewer" class="active">Fewer</button></div>')
        det_attr = ' data-files="fewer"' if foldable else ''
        out.append('        <details' + det_attr + '><summary class="cat-sum">'
                   '<div class="cat-name">' + RES_CHEV
                   + '<span class="cat-icon" style="background:var(--tint-' + key + ')">'
                   + RES_CAT_ICON[key] + '</span>' + html.escape(t) + cat_toggle + '</div>'
                   '<div class="req">' + html.escape(str(req)) + '</div>'
                   '<div class="bcol">' + _res_bars(c.get("bytes", [0]), cat_scale, t, ndev, multi)
                   + '</div>' + _res_sizes(c.get("bytes", [0]), ndev) + '</summary>')

        def asset_row(a, extra=""):
            ahost = _res_host(a.get("url"))
            host_html = ('<a class="host" href="' + attr(a.get("url", "")) + '" '
                         'target="_blank" rel="noopener"><span>' + html.escape(ahost)
                         + '</span>' + EXT_SVG + '</a>') if ahost else ""
            nm = str(a.get("name", ""))
            head, tail = _split_name(nm)
            name_html = ('<span class="nm" title="' + attr(nm) + '"><span class="nm-h">'
                         + html.escape(head) + '</span><span class="nm-t">'
                         + html.escape(tail) + '</span></span>')
            return ('          <div class="asset-row' + extra + '">'
                    '<div class="fname">' + name_html + host_html + '</div><div class="req"></div>'
                    '<div class="bcol">' + _res_bars(a.get("bytes", [0]), item_scale, t, ndev, multi)
                    + '</div>' + _res_sizes(a.get("bytes", [0]), ndev) + '</div>')

        for a in shown:
            out.append(asset_row(a))
        if foldable:
            for a in small:
                out.append(asset_row(a, " small"))
            fk = [sum((a.get("bytes") or [0])[i] for a in small) for i in range(ndev)]
            out.append('          <div class="sum-row" style="--tint:var(--tint-' + key + ')">'
                       '<div class="sum">+' + str(len(small)) + ' files under '
                       + str(SMALL_BYTES // 1024) + ' KB</div><div class="req"></div>'
                       '<div class="bcol"></div>' + _res_sizes(fk, ndev) + '</div>')
        out.append('        </details>')

    out.append('        <div class="res-foot"><div class="lbl">Total</div><div class="req">'
               + html.escape(str((res.get("total", {}).get("requests") or [""])[0]))
               + '</div><div class="bcol"></div>'
               + _res_sizes((res.get("total", {}).get("bytes") or [0]), ndev) + '</div>')
    out.append('      </div>')
    return "\n".join(out)


def build_findings_html(findings):
    rows = []
    for f in sorted_findings(findings):
        sev = str(f.get("severity", "low"))
        rows.append('      <article class="finding ' + sev + '">')
        rows.append('        <div class="finding-header">')
        if f.get("id"):
            rows.append('          <span class="finding-id">' + html.escape(str(f["id"])) + '</span>')
        rows.append('          <span class="finding-title">' + inline_html(f.get("title", "")) + '</span>')
        if f.get("savingsDisplay"):
            rows.append('          <span class="savings-chip">' + html.escape(f["savingsDisplay"]) + '</span>')
        if f.get("confirmed") is False:
            rows.append('          <span class="candidate-tag">Candidate</span>')
        rows.append('        </div>')
        rows.append('        <div class="finding-body">')
        for para in paragraphs(f.get("body")):
            rows.append('          <p>' + inline_html(para) + '</p>')
        if f.get("source"):
            rows.append('          <div class="finding-source">' + html.escape(f["source"]) + '</div>')
        rows.append('        </div>')
        rows.append('      </article>')
    return "\n".join(rows)


def build_tests_html(tests, label):
    rows = ['      <div class="subhead">' + html.escape(label) + '</div>',
            '      <ul class="test-list">']
    for t in tests:
        url = t.get("url", "")
        name = html.escape(t.get("label", ""))
        if url:
            rows.append('        <li><a href="' + attr(url) + '">' + name + '</a></li>')
        else:
            rows.append('        <li>' + name + '</li>')
    rows.append('      </ul>')
    return "\n".join(rows)


def build_bullets_html(items):
    rows = ['      <ul class="bullets">']
    for b in items:
        rows.append('        <li>' + inline_html(b) + '</li>')
    rows.append('      </ul>')
    return "\n".join(rows)


def build_html(data, template, slug):
    meta = data["meta"]
    nav = ['    <a href="#overview" class="nav-top-link active" data-target="overview">Overview</a>']
    body = []

    # Summary — part of the Overview nav entry (header + summary), no own link
    body.append(section("summary", "Summary",
                        prose_block(data.get("summary"), "summary-text")
                        or '    <p class="empty-note">No summary provided.</p>'))

    # Metrics
    nav.append(nav_link("metrics", "Metrics"))
    intro = prose_block((data.get("metrics") or {}).get("intro"), "section-intro")
    metrics_body = (intro + "\n" + build_metrics_html(data)) if intro else build_metrics_html(data)
    body.append(section("metrics", "Metrics", metrics_body))

    # Page resources
    if (data.get("resources") or {}).get("categories"):
        nav.append(nav_link("resources", "Page resources"))
        res_intro = prose_block((data.get("resources") or {}).get("intro"), "section-intro")
        res_body = (res_intro + "\n" + build_resources_html(data)) if res_intro \
            else build_resources_html(data)
        body.append(section("resources", "Page resources", res_body))

    # Architecture
    if str(data.get("architecture") or "").strip():
        nav.append(nav_link("architecture", "Site architecture"))
        body.append(section("architecture", "Site architecture", prose_block(data["architecture"])))

    # Performance
    perf = data.get("performance") or {}
    if perf.get("tests") or perf.get("findings"):
        nav.append(nav_link("performance", "Performance"))
        parts = []
        if perf.get("tests"):
            parts.append(build_tests_html(perf["tests"], "Tests"))
        if perf.get("findings"):
            parts.append('      <div class="subhead">Findings</div>')
            parts.append(build_findings_html(perf["findings"]))
        body.append(section("performance", "Performance", "\n".join(parts)))

    # Accessibility
    acc = data.get("accessibility") or {}
    if acc.get("tests") or acc.get("findings"):
        nav.append(nav_link("accessibility", "Accessibility"))
        parts = []
        if acc.get("tests"):
            parts.append(build_tests_html(acc["tests"], "Tests"))
        if acc.get("findings"):
            parts.append('      <div class="subhead">Findings</div>')
            parts.append(build_bullets_html(acc["findings"]))
        body.append(section("accessibility", "Accessibility", "\n".join(parts)))

    # Design & UX
    if data.get("ux"):
        nav.append(nav_link("ux", "Design & UX"))
        body.append(section("ux", "Design and user experience", build_bullets_html(data["ux"])))

    # Conclusions
    nav.append(nav_link("conclusions", "Conclusions"))
    body.append(section("conclusions", "Conclusions",
                        prose_block(data.get("conclusions"))
                        or '    <p class="empty-note">No conclusions provided.</p>'))

    # Priorities
    if data.get("priorities"):
        nav.append(nav_link("priorities", "Priority actions"))
        items = "\n".join('      <li>' + inline_html(p) + '</li>' for p in data["priorities"])
        body.append(section("priorities", "Priority actions",
                            '    <ol class="priority-list">\n' + items + '\n    </ol>'))

    # Glossary
    gkeys = used_glossary(data)
    if gkeys:
        nav.append(nav_link("glossary", "Glossary"))
        defs = []
        for k in gkeys:
            name, desc = GLOSSARY[k]
            defs.append('      <dt>' + html.escape(name) + '</dt>')
            defs.append('      <dd>' + html.escape(desc) + '</dd>')
        body.append(section("glossary", "Glossary", '    <dl class="glossary">\n'
                            + "\n".join(defs) + '\n    </dl>'))

    # Appendix
    runs = list(perf.get("tests") or []) + list(acc.get("tests") or [])
    if runs:
        nav.append(nav_link("appendix", "Appendix"))
        body.append(section("appendix", "Appendix — raw test runs",
                            build_tests_html(runs, "Test runs")))

    # Header meta — a URL button leads, then key/value chips in keeping with it.
    meta_rows = []
    if meta.get("url"):
        meta_rows.append('        <a class="url-btn" href="' + attr(meta["url"])
                         + '" target="_blank" rel="noopener">' + GLOBE_SVG
                         + '<span>' + html.escape(display_url(meta["url"])) + '</span>'
                         + EXT_SVG + '</a>')

    def meta_chip(label, value):
        return ('        <span class="meta-chip"><span class="mc-k">' + html.escape(label)
                + '</span><span class="mc-v">' + html.escape(str(value)) + '</span></span>')

    meta_rows.append(meta_chip("Date", meta.get("date", date.today().isoformat())))
    if meta.get("auditedBy"):
        meta_rows.append(meta_chip("By", meta["auditedBy"]))
    if meta.get("audience"):
        meta_rows.append(meta_chip("Audience", meta["audience"]))

    page_title = "Website Performance Review: " + site_name(meta)
    replacements = {
        "{{TITLE}}": html.escape(page_title),
        "{{SITENAME}}": html.escape(site_name(meta)),
        "{{HEADER_META}}": "\n".join(meta_rows),
        "{{SIDEBAR_NAV}}": "\n".join(nav),
        "{{CONTENT}}": "\n\n".join(body),
    }
    out = template
    for key, value in replacements.items():
        out = out.replace(key, value)
    return out


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Build performance audit reports.")
    parser.add_argument("audit", help="Path to audit.json")
    parser.add_argument("--out-dir", default=".", help="Output directory (default: .)")
    parser.add_argument("--template", default=None, help="Path to report-template.html")
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    template_path = Path(args.template) if args.template \
        else script_dir.parent / "assets" / "report-template.html"
    if not template_path.is_file():
        fail("HTML template not found: " + str(template_path))

    data = load_audit(args.audit)
    meta = data["meta"]
    slug = slugify(meta.get("slug") or meta.get("title") or "audit")

    out_dir = Path(args.out_dir)
    html_dir = out_dir / "html"
    out_dir.mkdir(parents=True, exist_ok=True)
    html_dir.mkdir(parents=True, exist_ok=True)

    md_path = out_dir / (slug + "-audit.md")
    html_path = html_dir / (slug + ".html")

    md_path.write_text(build_markdown(data), encoding="utf-8")
    template = template_path.read_text(encoding="utf-8")
    html_path.write_text(build_html(data, template, slug), encoding="utf-8")

    print("Performance audit reports written:")
    print("  Markdown : " + str(md_path))
    print("  HTML     : " + str(html_path))


if __name__ == "__main__":
    main()
