#!/usr/bin/env python3
"""Build a performance site-audit Markdown report and a static HTML report
from a structured audit.json file.

Usage:
    python3 build_report.py <audit.json> [--out-dir DIR] [--template FILE]

Outputs (under --out-dir, default current directory):
    <slug>-audit.md      Markdown report
    html/<slug>.html     Static HTML report (warm-stone, print-ready)

audit.json is the single source of truth; it is generated by the `draft` step,
not hand-edited. See REFERENCE.md for the schema, thresholds, and section rules.
"""

import argparse
import html
import json
import re
import sys
from datetime import date
from pathlib import Path

# ── Canonical thresholds: (good_max, ni_max). Below good_max = good;
#    up to ni_max = needs-improvement; above = poor. Units per REFERENCE.md. ──
THRESHOLDS = {
    "LCP": (2.5, 4.0),
    "CLS": (0.1, 0.25),
    "INP": (200, 500),
    "TBT": (200, 600),
    "SI":  (3.4, 5.8),
    "FCP": (1.8, 3.0),
}

METRIC_LABEL = {
    "LCP": "LCP", "CLS": "CLS", "INP": "INP", "TBT": "TBT",
    "SI": "Speed Index", "FCP": "FCP",
    "weight": "Page weight", "requests": "Requests",
}

GLOSSARY = {
    "LCP": ("Largest Contentful Paint",
            "Time to render the largest visible content above the fold. Good < 2.5 s, poor > 4 s."),
    "CLS": ("Cumulative Layout Shift",
            "Sum of unexpected layout movement during load. Good < 0.1, poor > 0.25."),
    "INP": ("Interaction to Next Paint",
            "Time from a user interaction to the next visual response. Good < 200 ms, poor > 500 ms. A field-data metric — not produced by a Lighthouse lab run."),
    "TBT": ("Total Blocking Time",
            "Lab proxy for INP: main-thread time blocked during load. Good < 200 ms."),
    "SI":  ("Speed Index",
            "How quickly content visually populates during load. Good < 3.4 s."),
    "FCP": ("First Contentful Paint",
            "Time to the first text or image painted. Good < 1.8 s."),
    "weight": ("Page weight",
               "Total bytes downloaded to render the page. More weight means longer load, more parsing, more mobile bandwidth."),
    "requests": ("Request count",
                 "Number of HTTP requests to render the page. High counts (> 100) usually signal concatenation/optimisation gaps."),
}

RATING_LABEL = {"good": "Good", "needs-improvement": "Needs improvement",
                "poor": "Poor", "neutral": "—", "na": "N/A"}


# ── Helpers ──────────────────────────────────────────────────────────────────

def fail(msg):
    sys.stderr.write("error: " + msg + "\n")
    sys.exit(1)


def slugify(text):
    s = re.sub(r"[^a-z0-9]+", "-", str(text).lower()).strip("-")
    return s or "audit"


def attr(text):
    return html.escape(str(text), quote=True)


def inline_html(text):
    out = html.escape(str(text), quote=False)
    out = re.sub(r"`([^`]+)`", lambda m: "<code>" + m.group(1) + "</code>", out)
    out = re.sub(r"\*\*(.+?)\*\*", lambda m: "<strong>" + m.group(1) + "</strong>", out)
    return out


def plain_text(text):
    t = re.sub(r"`([^`]+)`", r"\1", str(text))
    t = re.sub(r"\*\*(.+?)\*\*", r"\1", t)
    return t.strip()


def paragraphs(text):
    return [p.strip() for p in re.split(r"\n\s*\n", str(text or "")) if p.strip()]


def humanize_bytes(n):
    try:
        n = float(n)
    except (TypeError, ValueError):
        return str(n)
    if n >= 1024 * 1024:
        return "{0:.1f} MB".format(n / (1024 * 1024))
    if n >= 1024:
        return "{0:.0f} KB".format(n / 1024)
    return "{0:.0f} B".format(n)


def metric_display(key, value, given):
    if given:
        return given
    if value is None:
        return "—"
    if key in ("LCP", "SI", "FCP"):
        return "{0:.1f} s".format(value)
    if key == "CLS":
        return "{0:.2f}".format(value)
    if key in ("INP", "TBT"):
        return "{0} ms".format(int(round(value)))
    if key == "weight":
        return humanize_bytes(value)
    if key == "requests":
        return str(int(value))
    return str(value)


def metric_rating(key, value, given):
    if given:
        return given
    if value is None or key not in THRESHOLDS:
        return "neutral"
    good_max, ni_max = THRESHOLDS[key]
    if value < good_max:
        return "good"
    if value <= ni_max:
        return "needs-improvement"
    return "poor"


def score_rating(score):
    if score is None:
        return "neutral"
    if score >= 90:
        return "good"
    if score >= 50:
        return "needs-improvement"
    return "poor"


SEV_RANK = {"high": 0, "medium": 1, "low": 2}


def sorted_findings(findings):
    return sorted(findings or [], key=lambda f: SEV_RANK.get(f.get("severity"), 3))


# ── Load & validate ──────────────────────────────────────────────────────────

def load_audit(path):
    try:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail("audit file not found: " + str(path))
    except json.JSONDecodeError as e:
        fail("audit file is not valid JSON: " + str(e))
    if "meta" not in data:
        fail("audit file is missing the 'meta' object")
    return data


def used_glossary(data):
    keys = list(data.get("glossary") or [])
    if keys:
        return [k for k in GLOSSARY if k in keys]
    # fall back to whatever metric keys actually appear
    seen = set()
    for dev in (data.get("metrics") or {}).get("devices") or []:
        for item in dev.get("items") or []:
            seen.add(item.get("key"))
    return [k for k in GLOSSARY if k in seen]


# ── Markdown ─────────────────────────────────────────────────────────────────

def build_markdown(data):
    meta = data["meta"]
    out = []
    out.append("# " + meta.get("title", "Site Audit"))
    out.append("")
    bits = []
    if meta.get("url"):
        bits.append("**URL:** " + meta["url"])
    bits.append("**Date:** " + str(meta.get("date", date.today().isoformat())))
    if meta.get("scope"):
        bits.append("**Scope:** " + meta["scope"])
    if meta.get("audience"):
        bits.append("**Audience:** " + meta["audience"])
    out.append(" · ".join(bits))
    out.append("")

    # Executive summary
    out.append("## Executive summary")
    out.append("")
    for para in paragraphs(data.get("summary")):
        out.append(para)
        out.append("")

    # Metrics
    out.append("## Metrics")
    out.append("")
    for dev in (data.get("metrics") or {}).get("devices") or []:
        head = "### " + dev.get("name", "Device")
        if dev.get("perfScore") is not None:
            head += " — performance score {0}".format(int(dev["perfScore"]))
        out.append(head)
        if dev.get("source"):
            out.append("")
            out.append("_" + dev["source"] + "_")
        out.append("")
        out.append("| Metric | Value | Rating |")
        out.append("|---|---|---|")
        for item in dev.get("items") or []:
            key = item.get("key")
            disp = metric_display(key, item.get("value"), item.get("display"))
            rating = metric_rating(key, item.get("value"), item.get("rating"))
            out.append("| {0} | {1} | {2} |".format(
                METRIC_LABEL.get(key, key), disp, RATING_LABEL.get(rating, rating)))
        out.append("")

    # Architecture
    if str(data.get("architecture") or "").strip():
        out.append("## Site architecture")
        out.append("")
        for para in paragraphs(data["architecture"]):
            out.append(para)
            out.append("")

    # Performance
    perf = data.get("performance") or {}
    if perf.get("tests") or perf.get("findings") or perf.get("assets"):
        out.append("## Performance")
        out.append("")
        if perf.get("tests"):
            out.append("### Tests")
            out.append("")
            for t in perf["tests"]:
                out.append("- " + t.get("label", "") + ": " + t.get("url", ""))
            out.append("")
        if perf.get("findings"):
            out.append("### Findings")
            out.append("")
            for f in sorted_findings(perf["findings"]):
                title = "**{0}** — {1}".format(f.get("id", ""), f.get("title", ""))
                tags = []
                if f.get("savingsDisplay"):
                    tags.append(f["savingsDisplay"])
                if f.get("confirmed") is False:
                    tags.append("candidate")
                if tags:
                    title += " _(" + ", ".join(tags) + ")_"
                out.append(title)
                out.append("")
                for para in paragraphs(f.get("body")):
                    out.append(para)
                    out.append("")
        assets = perf.get("assets")
        if assets and assets.get("rows"):
            out.append("### Assets")
            out.append("")
            out.append("| Type | Requests | Size |")
            out.append("|---|---:|---:|")
            for r in assets["rows"]:
                out.append("| {0} | {1} | {2} |".format(
                    r.get("type", ""), r.get("requests", ""),
                    r.get("display", humanize_bytes(r.get("bytes", 0)))))
            if assets.get("total"):
                tot = assets["total"]
                out.append("| **Total** | {0} | {1} |".format(
                    tot.get("requests", ""),
                    tot.get("display", humanize_bytes(tot.get("bytes", 0)))))
            out.append("")

    # Accessibility
    acc = data.get("accessibility") or {}
    if acc.get("tests") or acc.get("findings"):
        out.append("## Accessibility")
        out.append("")
        if acc.get("tests"):
            out.append("### Tests")
            out.append("")
            for t in acc["tests"]:
                out.append("- " + t.get("label", "") + ": " + t.get("url", ""))
            out.append("")
        if acc.get("findings"):
            out.append("### Findings")
            out.append("")
            for b in acc["findings"]:
                out.append("- " + str(b))
            out.append("")

    # Design & UX
    if data.get("ux"):
        out.append("## Design and user experience")
        out.append("")
        for b in data["ux"]:
            out.append("- " + str(b))
        out.append("")

    # Conclusions
    out.append("## Conclusions")
    out.append("")
    for para in paragraphs(data.get("conclusions")):
        out.append(para)
        out.append("")

    # Priorities
    if data.get("priorities"):
        out.append("### Priority actions")
        out.append("")
        for i, p in enumerate(data["priorities"], 1):
            out.append("{0}. {1}".format(i, p))
        out.append("")

    # Glossary
    gkeys = used_glossary(data)
    if gkeys:
        out.append("## Glossary")
        out.append("")
        for k in gkeys:
            name, desc = GLOSSARY[k]
            out.append("- **{0}** — {1}".format(name, desc))
        out.append("")

    # Appendix
    runs = list(perf.get("tests") or []) + list(acc.get("tests") or [])
    if runs:
        out.append("## Appendix — raw test runs")
        out.append("")
        for t in runs:
            out.append("- " + t.get("label", "") + ": " + t.get("url", ""))
        out.append("")

    return "\n".join(out).rstrip() + "\n"


# ── HTML section builders ────────────────────────────────────────────────────

def nav_link(target, label):
    return ('    <a href="#' + attr(target) + '" class="nav-top-link" data-target="'
            + attr(target) + '">' + html.escape(label) + '</a>')


def prose_block(text, cls="prose"):
    paras = paragraphs(text)
    if not paras:
        return ""
    inner = "\n".join("      <p>" + inline_html(p) + "</p>" for p in paras)
    return '    <div class="' + cls + '">\n' + inner + '\n    </div>'


def section(sid, heading, body):
    return ('    <section class="content-section" id="' + attr(sid) + '">\n'
            '      <h2 class="section-heading">' + html.escape(heading) + '</h2>\n'
            + body + '\n    </section>')


def build_metrics_html(data):
    rows = []
    for dev in (data.get("metrics") or {}).get("devices") or []:
        rows.append('      <div class="device-block">')
        rows.append('        <div class="device-head">')
        rows.append('          <span class="device-name">' + html.escape(dev.get("name", "Device")) + '</span>')
        if dev.get("source"):
            rows.append('          <span class="device-source">' + html.escape(dev["source"]) + '</span>')
        if dev.get("perfScore") is not None:
            sc = int(dev["perfScore"])
            rows.append('          <span class="device-score ' + score_rating(sc)
                        + '">Score ' + str(sc) + '</span>')
        rows.append('        </div>')
        rows.append('        <div class="metric-grid">')
        for item in dev.get("items") or []:
            key = item.get("key")
            disp = metric_display(key, item.get("value"), item.get("display"))
            rating = metric_rating(key, item.get("value"), item.get("rating"))
            rows.append('          <div class="metric-card ' + rating + '">')
            rows.append('            <div class="metric-value">' + html.escape(disp) + '</div>')
            rows.append('            <div class="metric-label">'
                        + html.escape(METRIC_LABEL.get(key, str(key))) + '</div>')
            rows.append('          </div>')
        rows.append('        </div>')
        rows.append('      </div>')
    return "\n".join(rows)


def build_findings_html(findings):
    rows = []
    for f in sorted_findings(findings):
        sev = str(f.get("severity", "low"))
        rows.append('      <article class="finding ' + sev + '">')
        rows.append('        <div class="finding-header">')
        if f.get("id"):
            rows.append('          <span class="finding-id">' + html.escape(str(f["id"])) + '</span>')
        rows.append('          <span class="finding-title">' + inline_html(f.get("title", "")) + '</span>')
        if f.get("savingsDisplay"):
            rows.append('          <span class="savings-chip">' + html.escape(f["savingsDisplay"]) + '</span>')
        if f.get("confirmed") is False:
            rows.append('          <span class="candidate-tag">Candidate</span>')
        rows.append('        </div>')
        rows.append('        <div class="finding-body">')
        for para in paragraphs(f.get("body")):
            rows.append('          <p>' + inline_html(para) + '</p>')
        if f.get("source"):
            rows.append('          <div class="finding-source">' + html.escape(f["source"]) + '</div>')
        rows.append('        </div>')
        rows.append('      </article>')
    return "\n".join(rows)


def build_tests_html(tests, label):
    rows = ['      <div class="subhead">' + html.escape(label) + '</div>',
            '      <ul class="test-list">']
    for t in tests:
        url = t.get("url", "")
        name = html.escape(t.get("label", ""))
        if url:
            rows.append('        <li><a href="' + attr(url) + '">' + name + '</a></li>')
        else:
            rows.append('        <li>' + name + '</li>')
    rows.append('      </ul>')
    return "\n".join(rows)


def build_assets_html(assets):
    rows = ['      <div class="subhead">Assets</div>',
            '      <table class="data-table">',
            '        <thead><tr><th>Type</th><th>Requests</th><th>Size</th></tr></thead>',
            '        <tbody>']
    for r in assets.get("rows", []):
        disp = r.get("display", humanize_bytes(r.get("bytes", 0)))
        rows.append('          <tr><td>' + html.escape(str(r.get("type", "")))
                    + '</td><td class="num">' + html.escape(str(r.get("requests", "")))
                    + '</td><td class="num">' + html.escape(disp) + '</td></tr>')
    if assets.get("total"):
        tot = assets["total"]
        disp = tot.get("display", humanize_bytes(tot.get("bytes", 0)))
        rows.append('          <tr class="total"><td>Total</td><td class="num">'
                    + html.escape(str(tot.get("requests", ""))) + '</td><td class="num">'
                    + html.escape(disp) + '</td></tr>')
    rows += ['        </tbody>', '      </table>']
    return "\n".join(rows)


def build_bullets_html(items):
    rows = ['      <ul class="bullets">']
    for b in items:
        rows.append('        <li>' + inline_html(b) + '</li>')
    rows.append('      </ul>')
    return "\n".join(rows)


def build_html(data, template, slug):
    meta = data["meta"]
    nav = ['    <a href="#overview" class="nav-top-link active" data-target="overview">Overview</a>']
    body = []

    # Executive summary
    nav.append(nav_link("summary", "Executive summary"))
    body.append(section("summary", "Executive summary",
                        prose_block(data.get("summary"), "summary-text")
                        or '    <p class="empty-note">No summary provided.</p>'))

    # Metrics
    nav.append(nav_link("metrics", "Metrics"))
    body.append(section("metrics", "Metrics", build_metrics_html(data)))

    # Architecture
    if str(data.get("architecture") or "").strip():
        nav.append(nav_link("architecture", "Site architecture"))
        body.append(section("architecture", "Site architecture", prose_block(data["architecture"])))

    # Performance
    perf = data.get("performance") or {}
    if perf.get("tests") or perf.get("findings") or perf.get("assets"):
        nav.append(nav_link("performance", "Performance"))
        parts = []
        if perf.get("tests"):
            parts.append(build_tests_html(perf["tests"], "Tests"))
        if perf.get("findings"):
            parts.append('      <div class="subhead">Findings</div>')
            parts.append(build_findings_html(perf["findings"]))
        if perf.get("assets") and perf["assets"].get("rows"):
            parts.append(build_assets_html(perf["assets"]))
        body.append(section("performance", "Performance", "\n".join(parts)))

    # Accessibility
    acc = data.get("accessibility") or {}
    if acc.get("tests") or acc.get("findings"):
        nav.append(nav_link("accessibility", "Accessibility"))
        parts = []
        if acc.get("tests"):
            parts.append(build_tests_html(acc["tests"], "Tests"))
        if acc.get("findings"):
            parts.append('      <div class="subhead">Findings</div>')
            parts.append(build_bullets_html(acc["findings"]))
        body.append(section("accessibility", "Accessibility", "\n".join(parts)))

    # Design & UX
    if data.get("ux"):
        nav.append(nav_link("ux", "Design & UX"))
        body.append(section("ux", "Design and user experience", build_bullets_html(data["ux"])))

    # Conclusions
    nav.append(nav_link("conclusions", "Conclusions"))
    body.append(section("conclusions", "Conclusions",
                        prose_block(data.get("conclusions"))
                        or '    <p class="empty-note">No conclusions provided.</p>'))

    # Priorities
    if data.get("priorities"):
        nav.append(nav_link("priorities", "Priority actions"))
        items = "\n".join('      <li>' + inline_html(p) + '</li>' for p in data["priorities"])
        body.append(section("priorities", "Priority actions",
                            '    <ol class="priority-list">\n' + items + '\n    </ol>'))

    # Glossary
    gkeys = used_glossary(data)
    if gkeys:
        nav.append(nav_link("glossary", "Glossary"))
        defs = []
        for k in gkeys:
            name, desc = GLOSSARY[k]
            defs.append('      <dt>' + html.escape(name) + '</dt>')
            defs.append('      <dd>' + html.escape(desc) + '</dd>')
        body.append(section("glossary", "Glossary", '    <dl class="glossary">\n'
                            + "\n".join(defs) + '\n    </dl>'))

    # Appendix
    runs = list(perf.get("tests") or []) + list(acc.get("tests") or [])
    if runs:
        nav.append(nav_link("appendix", "Appendix"))
        body.append(section("appendix", "Appendix — raw test runs",
                            build_tests_html(runs, "Test runs")))

    # Header meta
    meta_rows = []
    if meta.get("url"):
        meta_rows.append('        <span>URL: <a href="' + attr(meta["url"]) + '">'
                         + html.escape(meta["url"]) + '</a></span>')
    meta_rows.append('        <span>Date: <strong>'
                     + html.escape(str(meta.get("date", date.today().isoformat()))) + '</strong></span>')
    if meta.get("auditedBy"):
        meta_rows.append('        <span>By: <strong>' + html.escape(meta["auditedBy"]) + '</strong></span>')
    if meta.get("audience"):
        meta_rows.append('        <span>Audience: <strong>' + html.escape(meta["audience"]) + '</strong></span>')

    replacements = {
        "{{TITLE}}": html.escape(meta.get("title", "Site Audit")),
        "{{SCOPE}}": html.escape(meta.get("scope", "Site audit")),
        "{{DATE}}": html.escape(str(meta.get("date", date.today().isoformat()))),
        "{{HEADER_META}}": "\n".join(meta_rows),
        "{{SIDEBAR_NAV}}": "\n".join(nav),
        "{{CONTENT}}": "\n\n".join(body),
    }
    out = template
    for key, value in replacements.items():
        out = out.replace(key, value)
    return out


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Build performance audit reports.")
    parser.add_argument("audit", help="Path to audit.json")
    parser.add_argument("--out-dir", default=".", help="Output directory (default: .)")
    parser.add_argument("--template", default=None, help="Path to report-template.html")
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    template_path = Path(args.template) if args.template \
        else script_dir.parent / "assets" / "report-template.html"
    if not template_path.is_file():
        fail("HTML template not found: " + str(template_path))

    data = load_audit(args.audit)
    meta = data["meta"]
    slug = slugify(meta.get("slug") or meta.get("title") or "audit")

    out_dir = Path(args.out_dir)
    html_dir = out_dir / "html"
    out_dir.mkdir(parents=True, exist_ok=True)
    html_dir.mkdir(parents=True, exist_ok=True)

    md_path = out_dir / (slug + "-audit.md")
    html_path = html_dir / (slug + ".html")

    md_path.write_text(build_markdown(data), encoding="utf-8")
    template = template_path.read_text(encoding="utf-8")
    html_path.write_text(build_html(data, template, slug), encoding="utf-8")

    print("Performance audit reports written:")
    print("  Markdown : " + str(md_path))
    print("  HTML     : " + str(html_path))


if __name__ == "__main__":
    main()
