#!/usr/bin/env python3
"""Build a performance site-audit Markdown report and a static HTML report
from a structured audit.json file.

Usage:
    python3 build_report.py <audit.json> [--out-dir DIR] [--template FILE]

Outputs (under --out-dir, default current directory):
    <slug>-audit.md      Markdown report
    html/<slug>.html     Static HTML report (warm-stone, print-ready)

audit.json is the single source of truth; it is generated by the `draft` step,
not hand-edited. See REFERENCE.md for the schema, thresholds, and section rules.
"""

import argparse
import html
import json
import re
import sys
from datetime import date
from pathlib import Path
from urllib.parse import urlparse

# ── Canonical thresholds: (good_max, ni_max). Below good_max = good;
#    up to ni_max = needs-improvement; above = poor. Units per REFERENCE.md. ──
THRESHOLDS = {
    "LCP": (2.5, 4.0),
    "CLS": (0.1, 0.25),
    "INP": (200, 500),
    "TBT": (200, 600),
    "SI":  (3.4, 5.8),
    "FCP": (1.8, 3.0),
}

METRIC_LABEL = {
    "LCP": "LCP", "CLS": "CLS", "INP": "INP", "TBT": "TBT",
    "SI": "Speed Index", "FCP": "FCP",
    "weight": "Page weight", "requests": "Requests",
}

GLOSSARY = {
    "LCP": ("Largest Contentful Paint",
            "Time to render the largest visible content above the fold. Good < 2.5 s, poor > 4 s."),
    "CLS": ("Cumulative Layout Shift",
            "Sum of unexpected layout movement during load. Good < 0.1, poor > 0.25."),
    "INP": ("Interaction to Next Paint",
            "Time from a user interaction to the next visual response. Good < 200 ms, poor > 500 ms. A field-data metric — not produced by a Lighthouse lab run."),
    "TBT": ("Total Blocking Time",
            "Lab proxy for INP: main-thread time blocked during load. Good < 200 ms."),
    "SI":  ("Speed Index",
            "How quickly content visually populates during load. Good < 3.4 s."),
    "FCP": ("First Contentful Paint",
            "Time to the first text or image painted. Good < 1.8 s."),
    "weight": ("Page weight",
               "Total bytes downloaded to render the page. More weight means longer load, more parsing, more mobile bandwidth."),
    "requests": ("Request count",
                 "Number of HTTP requests to render the page. High counts (> 100) usually signal concatenation/optimisation gaps."),
}

RATING_LABEL = {"good": "Good", "needs-improvement": "Needs improvement",
                "poor": "Poor", "neutral": "—", "na": "N/A"}

# ── Metrics-as-load-timeline presentation ──────────────────────────────────────
# Metric acronym for the rail's secondary line; full name comes from GLOSSARY.
ACR = {"LCP": "LCP", "CLS": "CLS", "INP": "INP", "TBT": "TBT", "SI": "SI", "FCP": "FCP"}

# Plain-language moment each metric marks in the page-load story.
MOMENT = {
    "FCP": "First paint", "LCP": "Main content in", "SI": "Visually complete",
    "TBT": "Ready to respond", "INP": "Stays snappy", "CLS": "Layout settled",
    "weight": "Page weight", "requests": "Requests",
}
RES_DESC = {"weight": "Total bytes downloaded", "requests": "HTTP requests made"}

# Phases of the load, in narrative order; the last (resources) renders as cards.
PHASES = [
    ("Painting the page", "How soon visitors see content", ["FCP", "LCP", "SI"]),
    ("Responding to input", "How quickly the page reacts", ["TBT", "INP"]),
    ("Visual stability", "Whether content stays put while loading", ["CLS"]),
    ("Page resources", "What the browser had to download", ["weight", "requests"]),
]
RES_KEYS = ("weight", "requests")
METRIC_ORDER = ["FCP", "LCP", "SI", "TBT", "CLS", "INP", "weight", "requests"]
SCORE_WORD = {"good": "Good", "needs-improvement": "Needs improvement", "poor": "Poor"}

RES_ICON = {
    "weight": ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" '
               'stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v12m0 0l-4-4m4 4l4-4M4 21h16"/></svg>'),
    "requests": ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" '
                 'stroke-linecap="round" stroke-linejoin="round"><path d="M4 8h15l-3-3M20 16H5l3 3"/></svg>'),
}
DEV_ICON = {
    "Desktop": ('<svg class="ic" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4">'
                '<rect x="1.5" y="2" width="13" height="9" rx="1"/><path d="M5.5 14h5M8 11v3"/></svg>'),
    "Mobile": ('<svg class="ic" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4">'
               '<rect x="4" y="1.5" width="8" height="13" rx="1.5"/><path d="M7 12.5h2"/></svg>'),
}
EXT_SVG = ('<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.6">'
           '<path d="M6 3.5H3.5v9h9V10M9.5 3.5H13V7M13 3.5L7.5 9"/></svg>')
GLOBE_SVG = ('<svg class="ic" viewBox="0 0 16 16" fill="none" stroke="currentColor" '
             'stroke-width="1.4"><circle cx="8" cy="8" r="6.5"/><path d="M1.5 8h13M8 1.5'
             'c1.8 1.7 2.8 4.1 2.8 6.5S9.8 12.8 8 14.5C6.2 12.8 5.2 10.4 5.2 8S6.2 3.2 8 1.5z"/></svg>')


def rail_pos(key, value):
    """Fraction 0–1 along a good→ni→poor rail (good 0–40%, ni 40–70%, poor 70–100%)."""
    good_max, ni_max = THRESHOLDS[key]
    if value <= 0:
        return 0.02
    if value < good_max:
        return (value / good_max) * 0.40
    if value <= ni_max:
        return 0.40 + ((value - good_max) / (ni_max - good_max)) * 0.30
    return 0.70 + min((value - ni_max) / ni_max, 1) * 0.30


def audit_type_from_source(src):
    s = str(src or "").strip()
    return s.split()[0] if s else "Audit"


def build_groups(data):
    """Normalise metrics into [{device, datasets:[overall?, ...audits]}].

    New schema: metrics.groups[].audits[]. Falls back to the legacy
    metrics.devices[] (each device becomes a single-audit group)."""
    metrics = data.get("metrics") or {}
    groups_raw = metrics.get("groups")
    if not groups_raw:
        groups_raw = [{"device": d.get("name", "Audit"),
                       "audits": [{"type": audit_type_from_source(d.get("source")),
                                   "source": d.get("source"), "perfScore": d.get("perfScore"),
                                   "reportUrl": d.get("reportUrl"), "items": d.get("items") or []}]}
                      for d in (metrics.get("devices") or [])]

    groups = []
    for g in groups_raw:
        audits = g.get("audits") or []
        device = g.get("device", "")
        audit_ds = []
        for a in audits:
            by_key = {it.get("key"): it for it in (a.get("items") or [])}
            audit_ds.append({
                "kind": "audit", "type": a.get("type", "Audit"), "device": device,
                "source": a.get("source", ""), "perfScore": a.get("perfScore"),
                "reportUrl": a.get("reportUrl"),
                "items": [by_key[k] for k in METRIC_ORDER if k in by_key],
            })

        # Per-metric mean across the audits that measured it.
        avg_items = []
        for k in METRIC_ORDER:
            vals = [it["value"] for a in audits for it in (a.get("items") or [])
                    if it.get("key") == k and it.get("value") is not None]
            if vals:
                avg_items.append({"key": k, "value": sum(vals) / len(vals)})
            elif any(it.get("key") == k for a in audits for it in (a.get("items") or [])):
                avg_items.append({"key": k, "value": None, "display": "lab N/A", "rating": "na"})

        scores = [a.get("perfScore") for a in audits if a.get("perfScore") is not None]
        overall = {
            "kind": "average", "type": "Overall", "device": device,
            "source": "Mean of {0} runs ({1})".format(
                len(audits), ", ".join(a.get("type", "Audit") for a in audits)),
            "sourceLinks": [{"type": a.get("type", "Audit"), "url": a.get("reportUrl")}
                            for a in audits if a.get("reportUrl")],
            # Only a genuine average earns a score; a lone contributing score
            # would just repeat its audit's tab, so leave it off the Overall tab.
            "perfScore": int(round(sum(scores) / len(scores))) if len(scores) > 1 else None,
            "items": avg_items,
        }
        # Skip the Overall tab when there's a single audit (it would just duplicate it).
        datasets = ([overall] if len(audits) > 1 else []) + audit_ds
        if datasets:
            groups.append({"device": device, "datasets": datasets})
    return groups


# ── Helpers ──────────────────────────────────────────────────────────────────

def fail(msg):
    sys.stderr.write("error: " + msg + "\n")
    sys.exit(1)


def slugify(text):
    s = re.sub(r"[^a-z0-9]+", "-", str(text).lower()).strip("-")
    return s or "audit"


def attr(text):
    return html.escape(str(text), quote=True)


def display_url(url):
    """Human-readable URL: drop scheme and a trailing slash, keep host + path."""
    s = re.sub(r"^https?://", "", str(url)).rstrip("/")
    return s or str(url)


def site_name(meta):
    """Short site label for headings: the URL host (sans www), else the title
    with a trailing ' — Site Audit' stripped."""
    url = meta.get("url")
    if url:
        host = urlparse(url if "://" in url else "http://" + url).hostname or ""
        host = re.sub(r"^www\.", "", host)
        if host:
            return host
    title = str(meta.get("title", "")).strip()
    return re.sub(r"\s*[—–-]\s*site audit$", "", title, flags=re.I) or "Site"


def inline_html(text):
    out = html.escape(str(text), quote=False)
    out = re.sub(r"`([^`]+)`", lambda m: "<code>" + m.group(1) + "</code>", out)
    out = re.sub(r"\*\*(.+?)\*\*", lambda m: "<strong>" + m.group(1) + "</strong>", out)
    return out


def plain_text(text):
    t = re.sub(r"`([^`]+)`", r"\1", str(text))
    t = re.sub(r"\*\*(.+?)\*\*", r"\1", t)
    return t.strip()


def paragraphs(text):
    return [p.strip() for p in re.split(r"\n\s*\n", str(text or "")) if p.strip()]


def humanize_bytes(n):
    try:
        n = float(n)
    except (TypeError, ValueError):
        return str(n)
    if n >= 1024 * 1024:
        return "{0:.1f} MB".format(n / (1024 * 1024))
    if n >= 1024:
        return "{0:.0f} KB".format(n / 1024)
    return "{0:.0f} B".format(n)


def metric_display(key, value, given):
    if given:
        return given
    if value is None:
        return "—"
    if key in ("LCP", "SI", "FCP"):
        return "{0:.1f} s".format(value)
    if key == "CLS":
        return "{0:.2f}".format(value)
    if key in ("INP", "TBT"):
        return "{0} ms".format(int(round(value)))
    if key == "weight":
        return humanize_bytes(value)
    if key == "requests":
        return str(int(value))
    return str(value)


def metric_rating(key, value, given):
    if given:
        return given
    if value is None or key not in THRESHOLDS:
        return "neutral"
    good_max, ni_max = THRESHOLDS[key]
    if value < good_max:
        return "good"
    if value <= ni_max:
        return "needs-improvement"
    return "poor"


def score_rating(score):
    if score is None:
        return "neutral"
    if score >= 90:
        return "good"
    if score >= 50:
        return "needs-improvement"
    return "poor"


SEV_RANK = {"high": 0, "medium": 1, "low": 2}


def sorted_findings(findings):
    return sorted(findings or [], key=lambda f: SEV_RANK.get(f.get("severity"), 3))


# ── Load & validate ──────────────────────────────────────────────────────────

def load_audit(path):
    try:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail("audit file not found: " + str(path))
    except json.JSONDecodeError as e:
        fail("audit file is not valid JSON: " + str(e))
    if "meta" not in data:
        fail("audit file is missing the 'meta' object")
    return data


def used_glossary(data):
    keys = list(data.get("glossary") or [])
    if keys:
        return [k for k in GLOSSARY if k in keys]
    # fall back to whatever metric keys actually appear
    seen = set()
    for g in build_groups(data):
        for ds in g["datasets"]:
            for item in ds["items"]:
                seen.add(item.get("key"))
    return [k for k in GLOSSARY if k in seen]


# ── Markdown ─────────────────────────────────────────────────────────────────

def build_markdown(data):
    meta = data["meta"]
    out = []
    out.append("# Website Performance Review: " + site_name(meta))
    out.append("")
    bits = []
    if meta.get("url"):
        bits.append("**URL:** " + meta["url"])
    bits.append("**Date:** " + str(meta.get("date", date.today().isoformat())))
    if meta.get("scope"):
        bits.append("**Scope:** " + meta["scope"])
    if meta.get("audience"):
        bits.append("**Audience:** " + meta["audience"])
    out.append(" · ".join(bits))
    out.append("")

    # Summary
    out.append("## Summary")
    out.append("")
    for para in paragraphs(data.get("summary")):
        out.append(para)
        out.append("")

    # Metrics
    out.append("## Metrics")
    out.append("")
    for g in build_groups(data):
        out.append("### " + (g["device"] or "Device"))
        out.append("")
        for ds in g["datasets"]:
            name = ("Overall average" if ds["kind"] == "average" else ds["type"])
            head = "#### " + name
            if ds.get("perfScore") is not None:
                head += " — performance score {0}".format(int(ds["perfScore"]))
            out.append(head)
            out.append("")
            meta_bits = []
            if ds.get("source"):
                meta_bits.append("_" + ds["source"] + "_")
            if ds.get("reportUrl"):
                meta_bits.append("[full report]({0})".format(ds["reportUrl"]))
            for l in ds.get("sourceLinks") or []:
                meta_bits.append("[{0}]({1})".format(l["type"], l["url"]))
            if meta_bits:
                out.append(" · ".join(meta_bits))
                out.append("")
            out.append("| Metric | Value | Rating |")
            out.append("|---|---|---|")
            for item in ds["items"]:
                key = item.get("key")
                disp = metric_display(key, item.get("value"), item.get("display"))
                rating = metric_rating(key, item.get("value"), item.get("rating"))
                out.append("| {0} | {1} | {2} |".format(
                    METRIC_LABEL.get(key, key), disp, RATING_LABEL.get(rating, rating)))
            out.append("")

    # Architecture
    if str(data.get("architecture") or "").strip():
        out.append("## Site architecture")
        out.append("")
        for para in paragraphs(data["architecture"]):
            out.append(para)
            out.append("")

    # Performance
    perf = data.get("performance") or {}
    if perf.get("tests") or perf.get("findings") or perf.get("assets"):
        out.append("## Performance")
        out.append("")
        if perf.get("tests"):
            out.append("### Tests")
            out.append("")
            for t in perf["tests"]:
                out.append("- " + t.get("label", "") + ": " + t.get("url", ""))
            out.append("")
        if perf.get("findings"):
            out.append("### Findings")
            out.append("")
            for f in sorted_findings(perf["findings"]):
                title = "**{0}** — {1}".format(f.get("id", ""), f.get("title", ""))
                tags = []
                if f.get("savingsDisplay"):
                    tags.append(f["savingsDisplay"])
                if f.get("confirmed") is False:
                    tags.append("candidate")
                if tags:
                    title += " _(" + ", ".join(tags) + ")_"
                out.append(title)
                out.append("")
                for para in paragraphs(f.get("body")):
                    out.append(para)
                    out.append("")
        assets = perf.get("assets")
        if assets and assets.get("rows"):
            out.append("### Assets")
            out.append("")
            out.append("| Type | Requests | Size |")
            out.append("|---|---:|---:|")
            for r in assets["rows"]:
                out.append("| {0} | {1} | {2} |".format(
                    r.get("type", ""), r.get("requests", ""),
                    r.get("display", humanize_bytes(r.get("bytes", 0)))))
            if assets.get("total"):
                tot = assets["total"]
                out.append("| **Total** | {0} | {1} |".format(
                    tot.get("requests", ""),
                    tot.get("display", humanize_bytes(tot.get("bytes", 0)))))
            out.append("")

    # Accessibility
    acc = data.get("accessibility") or {}
    if acc.get("tests") or acc.get("findings"):
        out.append("## Accessibility")
        out.append("")
        if acc.get("tests"):
            out.append("### Tests")
            out.append("")
            for t in acc["tests"]:
                out.append("- " + t.get("label", "") + ": " + t.get("url", ""))
            out.append("")
        if acc.get("findings"):
            out.append("### Findings")
            out.append("")
            for b in acc["findings"]:
                out.append("- " + str(b))
            out.append("")

    # Design & UX
    if data.get("ux"):
        out.append("## Design and user experience")
        out.append("")
        for b in data["ux"]:
            out.append("- " + str(b))
        out.append("")

    # Conclusions
    out.append("## Conclusions")
    out.append("")
    for para in paragraphs(data.get("conclusions")):
        out.append(para)
        out.append("")

    # Priorities
    if data.get("priorities"):
        out.append("### Priority actions")
        out.append("")
        for i, p in enumerate(data["priorities"], 1):
            out.append("{0}. {1}".format(i, p))
        out.append("")

    # Glossary
    gkeys = used_glossary(data)
    if gkeys:
        out.append("## Glossary")
        out.append("")
        for k in gkeys:
            name, desc = GLOSSARY[k]
            out.append("- **{0}** — {1}".format(name, desc))
        out.append("")

    # Appendix
    runs = list(perf.get("tests") or []) + list(acc.get("tests") or [])
    if runs:
        out.append("## Appendix — raw test runs")
        out.append("")
        for t in runs:
            out.append("- " + t.get("label", "") + ": " + t.get("url", ""))
        out.append("")

    return "\n".join(out).rstrip() + "\n"


# ── HTML section builders ────────────────────────────────────────────────────

def nav_link(target, label):
    return ('    <a href="#' + attr(target) + '" class="nav-top-link" data-target="'
            + attr(target) + '">' + html.escape(label) + '</a>')


def prose_block(text, cls="prose"):
    paras = paragraphs(text)
    if not paras:
        return ""
    inner = "\n".join("      <p>" + inline_html(p) + "</p>" for p in paras)
    return '    <div class="' + cls + '">\n' + inner + '\n    </div>'


def section(sid, heading, body):
    return ('    <section class="content-section" id="' + attr(sid) + '">\n'
            '      <h2 class="section-heading">' + html.escape(heading) + '</h2>\n'
            + body + '\n    </section>')


def _rail_row_html(item):
    key = item.get("key")
    rating = metric_rating(key, item.get("value"), item.get("rating"))
    disp = metric_display(key, item.get("value"), item.get("display"))
    has_rail = key in THRESHOLDS and item.get("value") is not None
    if has_rail:
        pos = rail_pos(key, item["value"]) * 100
        mid = ('<div class="rail-track"><span class="rail-marker ' + rating
               + '" style="left:{0:.1f}%"></span></div>'.format(pos))
    else:
        mid = '<div class="rail-track"><span class="rail-na">not measured in this run</span></div>'
    full = GLOSSARY.get(key, (key, ""))[0]
    return ('            <div class="tl-row"><div class="tl-label">'
            '<div class="moment">' + html.escape(MOMENT.get(key, key)) + '</div>'
            '<div class="metric"><b>' + html.escape(ACR.get(key, key)) + '</b> · '
            + html.escape(full) + '</div></div>' + mid
            + '<div class="rail-val ' + rating + '">' + html.escape(disp) + '</div></div>')


def _res_cards_html(items):
    cards = []
    for item in items:
        key = item.get("key")
        disp = metric_display(key, item.get("value"), item.get("display"))
        cards.append('<div class="res-card"><div class="rc-icon">' + RES_ICON.get(key, "")
                     + '</div><div class="rc-body"><div class="rc-val">' + html.escape(disp) + '</div>'
                     '<div class="rc-title">' + html.escape(MOMENT.get(key, key)) + '</div>'
                     '<div class="rc-desc">' + html.escape(RES_DESC.get(key, "")) + '</div></div></div>')
    return '            <div class="res-cards">' + "".join(cards) + '</div>'


def _timeline_html(dataset):
    by_key = {it.get("key"): it for it in dataset["items"]}
    rows = ['          <div class="tl">']
    for title, blurb, keys in PHASES:
        present = [by_key[k] for k in keys if k in by_key]
        if not present:
            continue
        is_res = set(keys) <= set(RES_KEYS)
        rows.append('            <div class="tl-phase"><div class="tl-spine">'
                    '<span class="tl-node' + (' muted' if is_res else '') + '"></span></div>')
        rows.append('              <div class="tl-body"><div class="tl-head">'
                    '<div class="tl-title">' + html.escape(title) + '</div>'
                    '<div class="tl-blurb">' + html.escape(blurb) + '</div></div>')
        rows.append(_res_cards_html(present) if is_res
                    else "\n".join(_rail_row_html(it) for it in present))
        rows.append('              </div></div>')
    rows.append('          </div>')
    return "\n".join(rows)


def _score_hero_html(dataset):
    if dataset.get("perfScore") is None:
        return ""
    sr = score_rating(dataset["perfScore"])
    sub = ("Averaged across runs" if dataset["kind"] == "average"
           else dataset["type"] + " lab score") + " · " + SCORE_WORD[sr]
    return ('          <div class="score-wrap"><div class="score-hero ' + sr + '">'
            '<div class="score-num">' + str(dataset["perfScore"])
            + '<span class="score-den">/100</span></div>'
            '<div class="score-meta"><div class="score-title">Performance score</div>'
            '<div class="score-sub">' + html.escape(sub) + '</div></div></div></div>')


def _panel_html(dataset, idx, active, device):
    cap_name = ("Overall average for " if dataset["kind"] == "average"
                else dataset["type"] + " for ") + device
    pill = '<span class="cap-avg">averaged</span>' if dataset["kind"] == "average" else ""
    link = ""
    if dataset["kind"] == "audit" and dataset.get("reportUrl"):
        link = ('<a class="cap-link" href="' + attr(dataset["reportUrl"])
                + '" target="_blank" rel="noopener">View full ' + html.escape(dataset["type"])
                + ' report ' + EXT_SVG + '</a>')
    elif dataset["kind"] == "average" and dataset.get("sourceLinks"):
        link = '<span class="cap-srclinks">' + "".join(
            '<a href="' + attr(l["url"]) + '" target="_blank" rel="noopener">'
            + html.escape(l["type"]) + ' ' + EXT_SVG + '</a>'
            for l in dataset["sourceLinks"]) + '</span>'
    cap = ('          <div class="panel-cap"><span class="cap-name">' + html.escape(cap_name)
           + '</span>' + pill + '<span class="cap-src">' + html.escape(dataset.get("source", ""))
           + '</span>' + link + '</div>')
    return ('        <div class="panel' + (' active' if active else '') + '" data-aud="' + str(idx) + '">\n'
            + cap + '\n' + _score_hero_html(dataset) + '\n' + _timeline_html(dataset) + '\n        </div>')


def build_metrics_html(data):
    groups = build_groups(data)
    if not groups:
        return '      <p class="empty-note">No metrics provided.</p>'
    out = ['      <div class="metrics-component">']
    if len(groups) > 1:
        out.append('        <div class="devbar"><span class="dev-lab">Tested on</span>')
        out.append('          <div class="seg">')
        for i, g in enumerate(groups):
            out.append('            <button class="seg-btn' + (' active' if i == 0 else '')
                       + '" data-dev="' + str(i) + '">' + DEV_ICON.get(g["device"], "")
                       + html.escape(g["device"]) + '</button>')
        out.append('          </div></div>')
    for i, g in enumerate(groups):
        out.append('        <div class="dev-group' + (' active' if i == 0 else '')
                   + '" data-dev="' + str(i) + '">')
        out.append('          <div class="tabrow">')
        for j, ds in enumerate(g["datasets"]):
            out.append('            <button class="atab' + (' active' if j == 0 else '')
                       + '" data-aud="' + str(j) + '">' + html.escape(ds["type"]) + '</button>')
        out.append('          </div>')
        out.append('          <div class="panel-stack">')
        for j, ds in enumerate(g["datasets"]):
            out.append(_panel_html(ds, j, j == 0, g["device"]))
        out.append('          </div>')
        out.append('        </div>')
    out.append('      </div>')
    return "\n".join(out)


def build_findings_html(findings):
    rows = []
    for f in sorted_findings(findings):
        sev = str(f.get("severity", "low"))
        rows.append('      <article class="finding ' + sev + '">')
        rows.append('        <div class="finding-header">')
        if f.get("id"):
            rows.append('          <span class="finding-id">' + html.escape(str(f["id"])) + '</span>')
        rows.append('          <span class="finding-title">' + inline_html(f.get("title", "")) + '</span>')
        if f.get("savingsDisplay"):
            rows.append('          <span class="savings-chip">' + html.escape(f["savingsDisplay"]) + '</span>')
        if f.get("confirmed") is False:
            rows.append('          <span class="candidate-tag">Candidate</span>')
        rows.append('        </div>')
        rows.append('        <div class="finding-body">')
        for para in paragraphs(f.get("body")):
            rows.append('          <p>' + inline_html(para) + '</p>')
        if f.get("source"):
            rows.append('          <div class="finding-source">' + html.escape(f["source"]) + '</div>')
        rows.append('        </div>')
        rows.append('      </article>')
    return "\n".join(rows)


def build_tests_html(tests, label):
    rows = ['      <div class="subhead">' + html.escape(label) + '</div>',
            '      <ul class="test-list">']
    for t in tests:
        url = t.get("url", "")
        name = html.escape(t.get("label", ""))
        if url:
            rows.append('        <li><a href="' + attr(url) + '">' + name + '</a></li>')
        else:
            rows.append('        <li>' + name + '</li>')
    rows.append('      </ul>')
    return "\n".join(rows)


def build_assets_html(assets):
    rows = ['      <div class="subhead">Assets</div>',
            '      <table class="data-table">',
            '        <thead><tr><th>Type</th><th>Requests</th><th>Size</th></tr></thead>',
            '        <tbody>']
    for r in assets.get("rows", []):
        disp = r.get("display", humanize_bytes(r.get("bytes", 0)))
        rows.append('          <tr><td>' + html.escape(str(r.get("type", "")))
                    + '</td><td class="num">' + html.escape(str(r.get("requests", "")))
                    + '</td><td class="num">' + html.escape(disp) + '</td></tr>')
    if assets.get("total"):
        tot = assets["total"]
        disp = tot.get("display", humanize_bytes(tot.get("bytes", 0)))
        rows.append('          <tr class="total"><td>Total</td><td class="num">'
                    + html.escape(str(tot.get("requests", ""))) + '</td><td class="num">'
                    + html.escape(disp) + '</td></tr>')
    rows += ['        </tbody>', '      </table>']
    return "\n".join(rows)


def build_bullets_html(items):
    rows = ['      <ul class="bullets">']
    for b in items:
        rows.append('        <li>' + inline_html(b) + '</li>')
    rows.append('      </ul>')
    return "\n".join(rows)


def build_html(data, template, slug):
    meta = data["meta"]
    nav = ['    <a href="#overview" class="nav-top-link active" data-target="overview">Overview</a>']
    body = []

    # Summary — part of the Overview nav entry (header + summary), no own link
    body.append(section("summary", "Summary",
                        prose_block(data.get("summary"), "summary-text")
                        or '    <p class="empty-note">No summary provided.</p>'))

    # Metrics
    nav.append(nav_link("metrics", "Metrics"))
    body.append(section("metrics", "Metrics", build_metrics_html(data)))

    # Architecture
    if str(data.get("architecture") or "").strip():
        nav.append(nav_link("architecture", "Site architecture"))
        body.append(section("architecture", "Site architecture", prose_block(data["architecture"])))

    # Performance
    perf = data.get("performance") or {}
    if perf.get("tests") or perf.get("findings") or perf.get("assets"):
        nav.append(nav_link("performance", "Performance"))
        parts = []
        if perf.get("tests"):
            parts.append(build_tests_html(perf["tests"], "Tests"))
        if perf.get("findings"):
            parts.append('      <div class="subhead">Findings</div>')
            parts.append(build_findings_html(perf["findings"]))
        if perf.get("assets") and perf["assets"].get("rows"):
            parts.append(build_assets_html(perf["assets"]))
        body.append(section("performance", "Performance", "\n".join(parts)))

    # Accessibility
    acc = data.get("accessibility") or {}
    if acc.get("tests") or acc.get("findings"):
        nav.append(nav_link("accessibility", "Accessibility"))
        parts = []
        if acc.get("tests"):
            parts.append(build_tests_html(acc["tests"], "Tests"))
        if acc.get("findings"):
            parts.append('      <div class="subhead">Findings</div>')
            parts.append(build_bullets_html(acc["findings"]))
        body.append(section("accessibility", "Accessibility", "\n".join(parts)))

    # Design & UX
    if data.get("ux"):
        nav.append(nav_link("ux", "Design & UX"))
        body.append(section("ux", "Design and user experience", build_bullets_html(data["ux"])))

    # Conclusions
    nav.append(nav_link("conclusions", "Conclusions"))
    body.append(section("conclusions", "Conclusions",
                        prose_block(data.get("conclusions"))
                        or '    <p class="empty-note">No conclusions provided.</p>'))

    # Priorities
    if data.get("priorities"):
        nav.append(nav_link("priorities", "Priority actions"))
        items = "\n".join('      <li>' + inline_html(p) + '</li>' for p in data["priorities"])
        body.append(section("priorities", "Priority actions",
                            '    <ol class="priority-list">\n' + items + '\n    </ol>'))

    # Glossary
    gkeys = used_glossary(data)
    if gkeys:
        nav.append(nav_link("glossary", "Glossary"))
        defs = []
        for k in gkeys:
            name, desc = GLOSSARY[k]
            defs.append('      <dt>' + html.escape(name) + '</dt>')
            defs.append('      <dd>' + html.escape(desc) + '</dd>')
        body.append(section("glossary", "Glossary", '    <dl class="glossary">\n'
                            + "\n".join(defs) + '\n    </dl>'))

    # Appendix
    runs = list(perf.get("tests") or []) + list(acc.get("tests") or [])
    if runs:
        nav.append(nav_link("appendix", "Appendix"))
        body.append(section("appendix", "Appendix — raw test runs",
                            build_tests_html(runs, "Test runs")))

    # Header meta — a URL button leads, then key/value chips in keeping with it.
    meta_rows = []
    if meta.get("url"):
        meta_rows.append('        <a class="url-btn" href="' + attr(meta["url"])
                         + '" target="_blank" rel="noopener">' + GLOBE_SVG
                         + '<span>' + html.escape(display_url(meta["url"])) + '</span>'
                         + EXT_SVG + '</a>')

    def meta_chip(label, value):
        return ('        <span class="meta-chip"><span class="mc-k">' + html.escape(label)
                + '</span><span class="mc-v">' + html.escape(str(value)) + '</span></span>')

    meta_rows.append(meta_chip("Date", meta.get("date", date.today().isoformat())))
    if meta.get("auditedBy"):
        meta_rows.append(meta_chip("By", meta["auditedBy"]))
    if meta.get("audience"):
        meta_rows.append(meta_chip("Audience", meta["audience"]))

    page_title = "Website Performance Review: " + site_name(meta)
    replacements = {
        "{{TITLE}}": html.escape(page_title),
        "{{SITENAME}}": html.escape(site_name(meta)),
        "{{HEADER_META}}": "\n".join(meta_rows),
        "{{SIDEBAR_NAV}}": "\n".join(nav),
        "{{CONTENT}}": "\n\n".join(body),
    }
    out = template
    for key, value in replacements.items():
        out = out.replace(key, value)
    return out


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Build performance audit reports.")
    parser.add_argument("audit", help="Path to audit.json")
    parser.add_argument("--out-dir", default=".", help="Output directory (default: .)")
    parser.add_argument("--template", default=None, help="Path to report-template.html")
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    template_path = Path(args.template) if args.template \
        else script_dir.parent / "assets" / "report-template.html"
    if not template_path.is_file():
        fail("HTML template not found: " + str(template_path))

    data = load_audit(args.audit)
    meta = data["meta"]
    slug = slugify(meta.get("slug") or meta.get("title") or "audit")

    out_dir = Path(args.out_dir)
    html_dir = out_dir / "html"
    out_dir.mkdir(parents=True, exist_ok=True)
    html_dir.mkdir(parents=True, exist_ok=True)

    md_path = out_dir / (slug + "-audit.md")
    html_path = html_dir / (slug + ".html")

    md_path.write_text(build_markdown(data), encoding="utf-8")
    template = template_path.read_text(encoding="utf-8")
    html_path.write_text(build_html(data, template, slug), encoding="utf-8")

    print("Performance audit reports written:")
    print("  Markdown : " + str(md_path))
    print("  HTML     : " + str(html_path))


if __name__ == "__main__":
    main()
