#!/usr/bin/env node
/**
 * css-token-audit — Markdown report builder (walking skeleton, slice #18).
 *
 * Renders a human-readable report from `audit.json`, the single generated
 * source of truth. audit.json is never hand-edited; re-run analyze.mjs to
 * regenerate it. This script is a pure renderer — it computes nothing new.
 *
 * The `schemaVersion` is the contract: this builder refuses an audit.json whose
 * MAJOR version it doesn't support, rather than silently mis-rendering.
 *
 * Usage:
 *   node build_report.mjs <audit.json> [--out <report.md>]
 */

import { readFileSync, writeFileSync } from 'node:fs';

export const SUPPORTED_MAJOR = 1;

const BASIS_NOTE = {
  universal: 'defensible anywhere',
  convention: "earned from this codebase's own patterns",
  'house-rule': 'an opt-in cross-project preference',
};

function parseArgs(argv) {
  const args = { input: null, out: null };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--out') args.out = argv[++i];
    else if (!args.input) args.input = a;
  }
  return args;
}

/** Refuse an audit whose schema major version we can't render. */
export function assertSchema(audit) {
  const v = audit && audit.schemaVersion;
  if (!v || typeof v !== 'string') {
    throw new Error('audit.json is missing a mandatory `schemaVersion`.');
  }
  const major = Number(v.split('.')[0]);
  if (!Number.isInteger(major) || major !== SUPPORTED_MAJOR) {
    throw new Error(
      `Unsupported schemaVersion ${v}: this builder handles major ${SUPPORTED_MAJOR}.x only. ` +
        'Re-run analyze.mjs with a matching version of the skill.'
    );
  }
}

const code = (s) => '`' + s + '`';

/** Render one location, preferring the selector (survives minification) and
 *  keeping file:line as a secondary hint. */
function fmtLocation(l) {
  const parts = [];
  if (l.selector) parts.push(code(l.selector));
  if (l.atScope) parts.push(`in ${code(l.atScope)}`);
  const fileLine = l.file ? `${l.file}:${l.line ?? '?'}` : null;
  if (fileLine) parts.push(parts.length ? `(${fileLine})` : code(fileLine));
  return parts.join(' ') || '_no location_';
}

function fmtLocations(locations) {
  if (!locations || !locations.length) return '_no location_';
  return locations.map(fmtLocation).join(', ');
}

/** Compact list of the selectors that consume a token. */
function fmtUsedIn(usedIn, total) {
  if (!usedIn || !usedIn.length) return '';
  const shown = usedIn.map((u) => code(u.selector)).join(', ');
  const more = total > usedIn.length ? `, +${total - usedIn.length} more` : '';
  return `${shown}${more}`;
}

/** Render the naming-taxonomy axis: an inferred grammar per tier, its
 *  consistency, prefix vocabulary, and any abbreviation conflicts. */
function renderNaming(L, naming) {
  L.push('## Naming taxonomy');
  L.push('');
  L.push(
    'The grammar is inferred **per tier** — the codebase runs one convention for global ' +
      '`:root` design tokens and another for block-scoped locals, so they are measured ' +
      'separately. Consistency is the share of a tier\'s tokens whose first segment is a ' +
      'recurring category/namespace prefix.'
  );
  L.push('');
  for (const [tierName, g] of Object.entries(naming.tiers)) {
    if (!g.tokenCount) continue;
    L.push(`### ${tierName} tier — ${g.tokenCount} tokens`);
    L.push('');
    L.push(`- **Inferred grammar:** ${code(g.template)}`);
    L.push(`- **Consistency:** ${Math.round(g.consistency * 100)}% follow a recurring prefix`);
    L.push(`- **Typical shape:** ${g.dominantSegmentCount} segments`);
    if (g.recurringPrefixes.length)
      L.push(`- **Category/namespace vocabulary:** ${g.recurringPrefixes.map((p) => code(p + '-')).join(', ')}`);
    if (g.singletonPrefixes.length)
      L.push(`- **One-of-a-kind prefixes:** ${g.singletonPrefixes.map((p) => code(p + '-')).join(', ')}`);
    if (g.abbreviationConflicts.length) {
      L.push('- **Abbreviation conflicts:**');
      for (const c of g.abbreviationConflicts)
        L.push(`  - "${c.concept}": ${c.forms.map((f) => `${code(f.form)} ×${f.count}`).join(' vs ')}`);
    }
    L.push('');
  }
}

export function renderReport(audit) {
  assertSchema(audit);
  const { meta, summary, model } = audit;
  const axis = model.axes.fanInOut;
  const L = [];

  L.push(`# CSS token audit — ${meta.project}`);
  L.push('');
  L.push(
    `_${meta.date} · ${meta.cssFiles} CSS file(s) · ${meta.declarations} custom-property ` +
      `declaration(s) · schema v${audit.schemaVersion} · generated by ${code(meta.generatedBy)}_`
  );
  L.push('');
  L.push(`Root: ${code(meta.root)}`);
  L.push('');

  // ── Parse-coverage caveat — a loud, unmissable warning. Parse errors mean
  //    the parser dropped part of a value to a raw string, so `var()` refs
  //    inside it are invisible: fan-in is undercounted and some "dead" tokens
  //    are false. On a preprocessed codebase this is the signal to point the
  //    audit at the COMPILED CSS, not the authored source (PRD §5.2). ──
  if (meta.parseErrors > 0) {
    L.push('> [!WARNING]');
    L.push(
      `> **${meta.parseErrors} parse error(s).** The parser could not fully read some values, ` +
        'so `var()` references inside them are missed — **fan-in is undercounted and some ' +
        '"dead" tokens below may be false.** This usually means the audited CSS is authored / ' +
        'pre-compilation (e.g. Sass, `@function`, custom syntax). Point the audit at the ' +
        '**compiled** CSS — the only place `var()` actually resolves. See the appendix.');
    L.push('');
  }

  // ── Tree-doubling caveat — distinct from the parse warning. Fires when the
  //    same tokens are defined identically across two top-level trees, i.e. the
  //    audit spanned a source tree AND its compiled build. Unlike the parse
  //    warning this can trip silently on all-valid plain CSS, so it names the
  //    specific problem and (when detectable) which tree is the build. ──
  if (audit.doubling) {
    const d = audit.doubling;
    const which = d.compiledDir ? ` (\`${d.compiledDir}/\` looks like the compiled build)` : '';
    L.push('> [!WARNING]');
    L.push(
      `> **Possible tree doubling.** ${d.sharedTokens} tokens ` +
        `(${Math.round(d.share * 100)}% of the set) are defined identically in **both** ` +
        `\`${d.dirA}/\` and \`${d.dirB}/\`${which} — you are probably auditing a source tree ` +
        '**and** its compiled build together. That double-counts every token and inflates the ' +
        'exact-duplicate findings below (they are this artifact, not real redundancy). ' +
        'Re-run against **one** tree — the compiled one.');
    L.push('');
  }

  // ── Overview ──
  L.push('## Overview');
  L.push('');
  L.push(`- **Tokens defined:** ${summary.tokenCount}`);
  L.push(`- **References (\`var()\` uses):** ${summary.referenceCount}`);
  L.push(`- **Dead** (defined, never referenced): ${summary.deadCount}`);
  L.push(`- **One-off** (referenced exactly once): ${summary.oneOffCount}`);
  L.push(`- **Dangling references** (used but never defined): ${summary.undefinedRefCount}`);
  L.push(`- **Findings:** ${summary.findingCount}`);
  L.push('');

  // ── Axis: fan-in / fan-out ──
  L.push('## Fan-in / fan-out');
  L.push('');
  L.push(
    'Fan-in is how many places reference a token (`var(--x)`); fan-out is how many other ' +
      'tokens a token references in its own value. High fan-in tokens are load-bearing — ' +
      'changing them ripples widely; zero fan-in is dead weight.'
  );
  L.push('');

  if (axis.loadBearing.length) {
    L.push(`### Load-bearing tokens (top ${axis.loadBearing.length} by fan-in)`);
    L.push('');
    L.push('Each shows fan-in / fan-out and a sample of the selectors that consume it ' +
      '(`var --token` means it feeds another token). Selectors survive minification where ' +
      'line numbers don\'t.');
    L.push('');
    for (const t of axis.loadBearing) {
      const used = fmtUsedIn(t.usedIn, t.usedInCount);
      L.push(`- ${code(t.name)} — fan-in ${t.fanIn}, fan-out ${t.fanOut}${used ? ` — used in ${used}` : ''}`);
    }
    L.push('');
  }

  if (axis.dead.length) {
    L.push(`### Dead tokens (${axis.dead.length})`);
    L.push('');
    L.push(axis.dead.map(code).join(', '));
    L.push('');
  }

  if (axis.oneOff.length) {
    L.push(`### One-off tokens (${axis.oneOff.length})`);
    L.push('');
    L.push('Referenced exactly once — candidates to inline, or leads for consolidation.');
    L.push('');
    L.push(axis.oneOff.map(code).join(', '));
    L.push('');
  }

  if (axis.undefinedReferences && axis.undefinedReferences.length) {
    L.push(`### Dangling references (${axis.undefinedReferences.length})`);
    L.push('');
    L.push('Referenced via `var()` but never defined in the audited CSS (a typo, a token ' +
      'defined elsewhere, or a runtime/JS-set property).');
    L.push('');
    L.push(axis.undefinedReferences.map((t) => `${code(t.name)} (×${t.fanIn})`).join(', '));
    L.push('');
  }

  // ── Naming taxonomy ──
  if (model.axes.naming) renderNaming(L, model.axes.naming);

  // ── Findings ──
  L.push('## Findings');
  L.push('');
  if (!audit.findings.length) {
    L.push('_No findings._');
    L.push('');
  } else {
    L.push(
      'Each finding cites a **basis** (the authority behind it) and a **confidence**. This ' +
        'tool never asserts "wrong" — it reports a deviation, its authority, and how sure it is.'
    );
    L.push('');
    const byType = new Map();
    for (const f of audit.findings) {
      if (!byType.has(f.type)) byType.set(f.type, []);
      byType.get(f.type).push(f);
    }
    for (const [type, group] of byType) {
      L.push(`### ${type} (${group.length})`);
      L.push('');
      for (const f of group) {
        L.push(`- **${f.id}** · ${f.title}`);
        L.push(`  - basis: \`${f.basis}\` · confidence: \`${f.confidence}\``);
        L.push(`  - where: ${fmtLocations(f.locations)}`);
        L.push(`  - ${f.evidence}`);
      }
      L.push('');
    }
  }

  // ── Appendix ──
  L.push('## Appendix');
  L.push('');
  L.push('**Basis** — the authority a finding is measured against:');
  for (const [k, v] of Object.entries(BASIS_NOTE)) L.push(`- \`${k}\` — ${v}.`);
  L.push('');
  L.push(
    '**Source of truth.** `audit.json` is generated by `analyze.mjs` from a deterministic ' +
      'css-tree parse — never hand-edited, and never read by eye. This report renders from it. ' +
      'The audit runs on the **compiled** CSS, the only place `var()` resolves; authored / ' +
      'preprocessor source is not a reliable graph (see the parse-coverage warning above).'
  );
  L.push('');

  return L.join('\n') + '\n';
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.input) {
    console.error('Usage: node build_report.mjs <audit.json> [--out <report.md>]');
    process.exit(2);
  }
  let audit;
  try {
    audit = JSON.parse(readFileSync(args.input, 'utf8'));
  } catch (err) {
    console.error(`Cannot read ${args.input}: ${err.message}`);
    process.exit(1);
  }
  let md;
  try {
    md = renderReport(audit);
  } catch (err) {
    console.error(`Refusing to build report: ${err.message}`);
    process.exit(1);
  }
  const out = args.out || `${audit.meta.slug || 'css-token'}-audit.md`;
  writeFileSync(out, md);
  console.error(`css-token-audit report → ${out}`);
}

export { parseArgs };

if (import.meta.url === `file://${process.argv[1]}`) main();
