#!/usr/bin/env node
/**
 * css-token-architect — render `target.json` → a Markdown target report (#35).
 *
 * `target.json` is the generated source of truth; this renders it. Same split as
 * the audit's `build_report.mjs`: never hand-edit either output — re-run
 * `formalize.mjs`. Refuses a target whose schema major it can't render, rather
 * than mis-rendering it.
 */

import { readFileSync, writeFileSync } from 'node:fs';

import { assertSchema } from './schema.mjs';

const code = (s) => '`' + s + '`';

function parseArgs(argv) {
  const args = { target: null, out: null };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--out') args.out = argv[++i];
    else if (!args.target) args.target = a;
  }
  return args;
}

/** One decision as a Markdown bullet: what it is, why, and where. */
function renderDecision(L, d) {
  const head = d.title || `${code(d.type || 'decision')} ${code(d.subject || d.fingerprint)}`;
  L.push(`- **${d.id}** — ${head}${d.stale ? ' _(stale — the current audit no longer raises this)_' : ''}`);
  if (d.note) L.push(`  - Why: ${d.note}`);
  if (d.basis) L.push(`  - Basis: ${d.basis}${d.confidence ? ` · confidence ${d.confidence}` : ''}`);
  for (const loc of d.locations || []) {
    const where = [loc.selector, loc.file && `${loc.file}${loc.line ? `:${loc.line}` : ''}`].filter(Boolean);
    if (where.length) L.push(`  - ${where.map(code).join(' — ')}`);
  }
}

export function renderTargetReport(target) {
  assertSchema(target, 'target.json');
  const { meta, summary, decisions, constraints } = target;
  const L = [];

  L.push(`# CSS token target architecture: ${meta.project || meta.slug || 'untitled'}`);
  L.push('');
  L.push(
    `Generated by \`css-token-architect\` on ${meta.date} from the audit of ${code(meta.root || 'the CSS tree')}. ` +
      'This file is **generated** — never hand-edit it. Re-run `formalize.mjs`; ' +
      'edit the **conventions file** instead, which is where the decisions come from.'
  );
  L.push('');

  const changes = decisions.filter((d) => d.intent === 'change');
  const keeps = decisions.filter((d) => d.intent === 'keep');

  L.push('## Overview');
  L.push('');
  L.push(`- ${summary.decisionCount} decision(s) carried from the conventions file`);
  L.push(`  - ${summary.changeCount} to change · ${summary.keepCount} deliberately kept`);
  if (summary.staleCount) L.push(`  - ${summary.staleCount} stale (the audit no longer raises them)`);
  L.push(`- ${summary.constraintCount} constraint(s) from promoted house rules`);
  L.push('');

  if (!summary.decisionCount && !summary.constraintCount) {
    L.push('**No decisions yet.** Nothing has been disposed of in the conventions file, so the');
    L.push('target is an empty shell. Run `/css-token-audit curate` first — the target is only');
    L.push('ever as good as the dispositions feeding it.');
    L.push('');
  }

  if (changes.length) {
    L.push('## Changes');
    L.push('');
    L.push('Findings a human marked `fix` — the refactor leads this target commits to.');
    L.push('');
    for (const d of changes) renderDecision(L, d);
    L.push('');
  }

  if (keeps.length) {
    L.push('## Deliberately kept');
    L.push('');
    L.push('Findings a human `accept`ed. **Intentional** — later formalization passes must not');
    L.push('"fix" these.');
    L.push('');
    for (const d of keeps) renderDecision(L, d);
    L.push('');
  }

  if (constraints.length) {
    L.push('## Constraints');
    L.push('');
    L.push('Promoted house rules — standing rules the whole target must satisfy.');
    L.push('');
    for (const c of constraints) {
      L.push(`- **${c.id}** — ${code(c.rule)}${c.title ? ` — ${c.title}` : ''}`);
      if (c.tier) L.push(`  - Tier: ${code(c.tier)}`);
      if (c.allowed) L.push(`  - Allowed: ${c.allowed.map(code).join(', ')}`);
      if (c.note) L.push(`  - Why: ${c.note}`);
    }
    L.push('');
  }

  return L.join('\n');
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.target) {
    console.error('usage: build_target_report.mjs <target.json> [--out report.md]');
    process.exit(1);
  }
  const target = JSON.parse(readFileSync(args.target, 'utf8'));
  const md = renderTargetReport(target);
  if (args.out) {
    writeFileSync(args.out, md);
    console.error(`css-token-architect: wrote ${args.out}`);
  } else {
    process.stdout.write(md);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) main();

export { parseArgs };
